PROC SQL;
CREATE TABLE WORK.&STATE._RATE_DRIVER03 AS
	SELECT
		 RateLinkID
		,MAX(ZipCode) as Dr_Res_ZIP
		,COUNT(RateDriverID) AS Num_Drivers
		,SUM(CASE WHEN Excluded = 1 THEN 1 ELSE 0 END) as Num_Excl_Drivers
		,SUM(InternatDL) as InternatDL_Cnt
		,MAX(CASE WHEN RANKING = 1 THEN RateDriverId ELSE 0 END) AS RateDriverId01
		,MAX(CASE WHEN RANKING = 2 THEN RateDriverId ELSE 0 END) AS RateDriverId02
		,MAX(CASE WHEN RANKING = 3 THEN RateDriverId ELSE 0 END) AS RateDriverId03
/*		,MAX(CASE WHEN RANKING = 4 THEN RateDriverId ELSE 0 END) AS RateDriverId04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN RateDriverId ELSE 0 END) AS RateDriverId05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN RateDriverId ELSE 0 END) AS RateDriverId99*/
		
		,MAX(CASE WHEN RANKING = 1 THEN Age ELSE 0 END) AS Age01
		,MAX(CASE WHEN RANKING = 2 THEN Age ELSE 0 END) AS Age02
		,MAX(CASE WHEN RANKING = 3 THEN Age ELSE 0 END) AS Age03
/*		,MAX(CASE WHEN RANKING = 4 THEN Age ELSE 0 END) AS Age04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN Age ELSE 0 END) AS Age05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN Age ELSE 0 END) AS Age99*/

		,MAX(CASE WHEN RANKING = 1 THEN Employed ELSE "" END) AS Employed01
		,MAX(CASE WHEN RANKING = 2 THEN Employed ELSE "" END) AS Employed02
		,MAX(CASE WHEN RANKING = 3 THEN Employed ELSE "" END) AS Employed03
/*		,MAX(CASE WHEN RANKING = 4 THEN Employed ELSE "" END) AS Employed04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN Employed ELSE "" END) AS Employed05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN Employed ELSE "" END) AS Employed99*/

		,MAX(CASE WHEN RANKING = 1 THEN Excluded ELSE 0 END) AS Excluded01
		,MAX(CASE WHEN RANKING = 2 THEN Excluded ELSE 0 END) AS Excluded02
		,MAX(CASE WHEN RANKING = 3 THEN Excluded ELSE 0 END) AS Excluded03
/*		,MAX(CASE WHEN RANKING = 4 THEN Excluded ELSE 0 END) AS Excluded04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN Excluded ELSE 0 END) AS Excluded05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN Excluded ELSE 0 END) AS Excluded99*/

		,MAX(CASE WHEN RANKING = 1 THEN InternatDL ELSE 0 END) AS InternatDL01
		,MAX(CASE WHEN RANKING = 2 THEN InternatDL ELSE 0 END) AS InternatDL02
		,MAX(CASE WHEN RANKING = 3 THEN InternatDL ELSE 0 END) AS InternatDL03
/*		,MAX(CASE WHEN RANKING = 4 THEN InternatDL ELSE 0 END) AS InternatDL04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN InternatDL ELSE 0 END) AS InternatDL05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN InternatDL ELSE 0 END) AS InternatDL99*/


		,MAX(CASE WHEN RANKING = 1 THEN Licensed ELSE 0 END) AS Licensed01
		,MAX(CASE WHEN RANKING = 2 THEN Licensed ELSE 0 END) AS Licensed02
		,MAX(CASE WHEN RANKING = 3 THEN Licensed ELSE 0 END) AS Licensed03
/*		,MAX(CASE WHEN RANKING = 4 THEN Licensed ELSE 0 END) AS Licensed04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN Licensed ELSE 0 END) AS Licensed05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN Licensed ELSE 0 END) AS Licensed99*/

		,MAX(CASE WHEN RANKING = 1 THEN Marital ELSE "" END) AS Marital01
		,MAX(CASE WHEN RANKING = 2 THEN Marital ELSE "" END) AS Marital02
		,MAX(CASE WHEN RANKING = 3 THEN Marital ELSE "" END) AS Marital03
/*		,MAX(CASE WHEN RANKING = 4 THEN Marital ELSE "" END) AS Marital04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN Marital ELSE "" END) AS Marital05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN Marital ELSE "" END) AS Marital99*/

		,MAX(CASE WHEN RANKING = 1 THEN MonthsLicensed ELSE 0 END) AS MonthsLicensed01
		,MAX(CASE WHEN RANKING = 2 THEN MonthsLicensed ELSE 0 END) AS MonthsLicensed02
		,MAX(CASE WHEN RANKING = 3 THEN MonthsLicensed ELSE 0 END) AS MonthsLicensed03
/*		,MAX(CASE WHEN RANKING = 4 THEN MonthsLicensed ELSE 0 END) AS MonthsLicensed04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN MonthsLicensed ELSE 0 END) AS MonthsLicensed05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN MonthsLicensed ELSE 0 END) AS MonthsLicensed99*/

		,MAX(CASE WHEN RANKING = 1 THEN PriorDaysLapse ELSE 0 END) AS PriorDaysLapse01
		,MAX(CASE WHEN RANKING = 2 THEN PriorDaysLapse ELSE 0 END) AS PriorDaysLapse02
		,MAX(CASE WHEN RANKING = 3 THEN PriorDaysLapse ELSE 0 END) AS PriorDaysLapse03
/*		,MAX(CASE WHEN RANKING = 4 THEN PriorDaysLapse ELSE 0 END) AS PriorDaysLapse04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN PriorDaysLapse ELSE 0 END) AS PriorDaysLapse05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN PriorDaysLapse ELSE 0 END) AS PriorDaysLapse99*/

		,MAX(CASE WHEN RANKING = 1 THEN PriorInsurance ELSE 0 END) AS PriorInsurance01
		,MAX(CASE WHEN RANKING = 2 THEN PriorInsurance ELSE 0 END) AS PriorInsurance02
		,MAX(CASE WHEN RANKING = 3 THEN PriorInsurance ELSE 0 END) AS PriorInsurance03
/*		,MAX(CASE WHEN RANKING = 4 THEN PriorInsurance ELSE 0 END) AS PriorInsurance04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN PriorInsurance ELSE 0 END) AS PriorInsurance05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN PriorInsurance ELSE 0 END) AS PriorInsurance99*/

		,MAX(CASE WHEN RANKING = 1 THEN PriorMonthsCovg ELSE 0 END) AS PriorMonthsCovg01
		,MAX(CASE WHEN RANKING = 2 THEN PriorMonthsCovg ELSE 0 END) AS PriorMonthsCovg02
		,MAX(CASE WHEN RANKING = 3 THEN PriorMonthsCovg ELSE 0 END) AS PriorMonthsCovg03
/*		,MAX(CASE WHEN RANKING = 4 THEN PriorMonthsCovg ELSE 0 END) AS PriorMonthsCovg04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN PriorMonthsCovg ELSE 0 END) AS PriorMonthsCovg05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN PriorMonthsCovg ELSE 0 END) AS PriorMonthsCovg99*/

		,MAX(CASE WHEN RANKING = 1 THEN Relation ELSE "" END) AS Relation01
		,MAX(CASE WHEN RANKING = 2 THEN Relation ELSE "" END) AS Relation02
		,MAX(CASE WHEN RANKING = 3 THEN Relation ELSE "" END) AS Relation03
/*		,MAX(CASE WHEN RANKING = 4 THEN Relation ELSE "" END) AS Relation04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN Relation ELSE "" END) AS Relation05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN Relation ELSE "" END) AS Relation99*/

		,MAX(CASE WHEN RANKING = 1 THEN ResidencyStatus ELSE "" END) AS ResidencyStatus01
		,MAX(CASE WHEN RANKING = 2 THEN ResidencyStatus ELSE "" END) AS ResidencyStatus02
		,MAX(CASE WHEN RANKING = 3 THEN ResidencyStatus ELSE "" END) AS ResidencyStatus03
/*		,MAX(CASE WHEN RANKING = 4 THEN ResidencyStatus ELSE "" END) AS ResidencyStatus04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN ResidencyStatus ELSE "" END) AS ResidencyStatus05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN ResidencyStatus ELSE "" END) AS ResidencyStatus99*/

		,MAX(CASE WHEN RANKING = 1 THEN ResidencyType ELSE "" END) AS ResidencyType01
		,MAX(CASE WHEN RANKING = 2 THEN ResidencyType ELSE "" END) AS ResidencyType02
		,MAX(CASE WHEN RANKING = 3 THEN ResidencyType ELSE "" END) AS ResidencyType03
/*		,MAX(CASE WHEN RANKING = 4 THEN ResidencyType ELSE "" END) AS ResidencyType04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN ResidencyType ELSE "" END) AS ResidencyType05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN ResidencyType ELSE "" END) AS ResidencyType99*/

		,MAX(CASE WHEN RANKING = 1 THEN Sex ELSE "" END) AS Sex01
		,MAX(CASE WHEN RANKING = 2 THEN Sex ELSE "" END) AS Sex02
		,MAX(CASE WHEN RANKING = 3 THEN Sex ELSE "" END) AS Sex03
/*		,MAX(CASE WHEN RANKING = 4 THEN Sex ELSE "" END) AS Sex04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN Sex ELSE "" END) AS Sex05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN Sex ELSE "" END) AS Sex99*/

		,MAX(CASE WHEN RANKING = 1 THEN SR22 ELSE 0 END) AS SR2201
		,MAX(CASE WHEN RANKING = 2 THEN SR22 ELSE 0 END) AS SR2202
		,MAX(CASE WHEN RANKING = 3 THEN SR22 ELSE 0 END) AS SR2203
/*		,MAX(CASE WHEN RANKING = 4 THEN SR22 ELSE 0 END) AS SR2204*/
/*		,MAX(CASE WHEN RANKING = 5 THEN SR22 ELSE 0 END) AS SR2205*/
/*		,MAX(CASE WHEN RANKING > 5 THEN SR22 ELSE 0 END) AS SR2299*/

		,MAX(CASE WHEN RANKING = 1 THEN StateLicensed ELSE "" END) AS StateLicensed01
		,MAX(CASE WHEN RANKING = 2 THEN StateLicensed ELSE "" END) AS StateLicensed02
		,MAX(CASE WHEN RANKING = 3 THEN StateLicensed ELSE "" END) AS StateLicensed03
/*		,MAX(CASE WHEN RANKING = 4 THEN StateLicensed ELSE "" END) AS StateLicensed04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN StateLicensed ELSE "" END) AS StateLicensed05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN StateLicensed ELSE "" END) AS StateLicensed99*/

		,MAX(CASE WHEN RANKING = 1 THEN SuspendedLic ELSE 0 END) AS SuspendedLic01
		,MAX(CASE WHEN RANKING = 2 THEN SuspendedLic ELSE 0 END) AS SuspendedLic02
		,MAX(CASE WHEN RANKING = 3 THEN SuspendedLic ELSE 0 END) AS SuspendedLic03
/*		,MAX(CASE WHEN RANKING = 4 THEN SuspendedLic ELSE 0 END) AS SuspendedLic04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN SuspendedLic ELSE 0 END) AS SuspendedLic05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN SuspendedLic ELSE 0 END) AS SuspendedLic99*/

		,MAX(CASE WHEN RANKING = 1 THEN PriorCarrierId ELSE 0 END) AS PriorCarrierId01
		,MAX(CASE WHEN RANKING = 2 THEN PriorCarrierId ELSE 0 END) AS PriorCarrierId02
		,MAX(CASE WHEN RANKING = 3 THEN PriorCarrierId ELSE 0 END) AS PriorCarrierId03
/*		,MAX(CASE WHEN RANKING = 4 THEN PriorCarrierId ELSE 0 END) AS PriorCarrierId04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN PriorCarrierId ELSE 0 END) AS PriorCarrierId05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN PriorCarrierId ELSE 0 END) AS PriorCarrierId99*/

		,MAX(CASE WHEN RANKING = 1 THEN PriorLiabLimits1 ELSE 0 END) AS PriorLiabLimits101
		,MAX(CASE WHEN RANKING = 2 THEN PriorLiabLimits1 ELSE 0 END) AS PriorLiabLimits102
		,MAX(CASE WHEN RANKING = 3 THEN PriorLiabLimits1 ELSE 0 END) AS PriorLiabLimits103
/*		,MAX(CASE WHEN RANKING = 4 THEN PriorLiabLimits1 ELSE 0 END) AS PriorLiabLimits104*/
/*		,MAX(CASE WHEN RANKING = 5 THEN PriorLiabLimits1 ELSE 0 END) AS PriorLiabLimits105*/
/*		,MAX(CASE WHEN RANKING > 5 THEN PriorLiabLimits1 ELSE 0 END) AS PriorLiabLimits199*/

		,MAX(CASE WHEN RANKING = 1 THEN PriorLiabLimits2 ELSE 0 END) AS PriorLiabLimits201
		,MAX(CASE WHEN RANKING = 2 THEN PriorLiabLimits2 ELSE 0 END) AS PriorLiabLimits202
		,MAX(CASE WHEN RANKING = 3 THEN PriorLiabLimits2 ELSE 0 END) AS PriorLiabLimits203
/*		,MAX(CASE WHEN RANKING = 4 THEN PriorLiabLimits2 ELSE 0 END) AS PriorLiabLimits204*/
/*		,MAX(CASE WHEN RANKING = 5 THEN PriorLiabLimits2 ELSE 0 END) AS PriorLiabLimits205*/
/*		,MAX(CASE WHEN RANKING > 5 THEN PriorLiabLimits2 ELSE 0 END) AS PriorLiabLimits299*/

		,MAX(CASE WHEN RANKING = 1 THEN PriorLiabLimits3 ELSE 0 END) AS PriorLiabLimits301
		,MAX(CASE WHEN RANKING = 2 THEN PriorLiabLimits3 ELSE 0 END) AS PriorLiabLimits302
		,MAX(CASE WHEN RANKING = 3 THEN PriorLiabLimits3 ELSE 0 END) AS PriorLiabLimits303
/*		,MAX(CASE WHEN RANKING = 4 THEN PriorLiabLimits3 ELSE 0 END) AS PriorLiabLimits304*/
/*		,MAX(CASE WHEN RANKING = 5 THEN PriorLiabLimits3 ELSE 0 END) AS PriorLiabLimits305*/
/*		,MAX(CASE WHEN RANKING > 5 THEN PriorLiabLimits3 ELSE 0 END) AS PriorLiabLimits399*/

/*		,MAX(CASE WHEN RANKING = 1 THEN IndustryId ELSE "" END) AS IndustryId01*/
/*		,MAX(CASE WHEN RANKING = 2 THEN IndustryId ELSE "" END) AS IndustryId02*/
/*		,MAX(CASE WHEN RANKING = 3 THEN IndustryId ELSE "" END) AS IndustryId03*/
/*		,MAX(CASE WHEN RANKING = 4 THEN IndustryId ELSE "" END) AS IndustryId04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN IndustryId ELSE "" END) AS IndustryId05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN IndustryId ELSE "" END) AS IndustryId99*/
/**/
/*		,MAX(CASE WHEN RANKING = 1 THEN OccupationId ELSE "" END) AS OccupationId01*/
/*		,MAX(CASE WHEN RANKING = 2 THEN OccupationId ELSE "" END) AS OccupationId02*/
/*		,MAX(CASE WHEN RANKING = 3 THEN OccupationId ELSE "" END) AS OccupationId03*/
/*		,MAX(CASE WHEN RANKING = 4 THEN OccupationId ELSE "" END) AS OccupationId04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN OccupationId ELSE "" END) AS OccupationId05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN OccupationId ELSE "" END) AS OccupationId99*/

		,MAX(CASE WHEN RANKING = 1 THEN PrimaryCar ELSE 0 END) AS PrimaryCar01
		,MAX(CASE WHEN RANKING = 2 THEN PrimaryCar ELSE 0 END) AS PrimaryCar02
		,MAX(CASE WHEN RANKING = 3 THEN PrimaryCar ELSE 0 END) AS PrimaryCar03
/*		,MAX(CASE WHEN RANKING = 4 THEN PrimaryCar ELSE 0 END) AS PrimaryCar04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN PrimaryCar ELSE 0 END) AS PrimaryCar05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN PrimaryCar ELSE 0 END) AS PrimaryCar99*/

		,MAX(CASE WHEN RANKING = 1 THEN EducationLevel ELSE "" END) AS EducationLevel01
		,MAX(CASE WHEN RANKING = 2 THEN EducationLevel ELSE "" END) AS EducationLevel02
		,MAX(CASE WHEN RANKING = 3 THEN EducationLevel ELSE "" END) AS EducationLevel03
/*		,MAX(CASE WHEN RANKING = 4 THEN EducationLevel ELSE "" END) AS EducationLevel04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN EducationLevel ELSE "" END) AS EducationLevel05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN EducationLevel ELSE "" END) AS EducationLevel99*/

/*		,MAX(CASE WHEN RANKING = 1 THEN TVDL ELSE 0 END) AS TVDL01*/
/*		,MAX(CASE WHEN RANKING = 2 THEN TVDL ELSE 0 END) AS TVDL02*/
/*		,MAX(CASE WHEN RANKING = 3 THEN TVDL ELSE 0 END) AS TVDL03*/
/*		,MAX(CASE WHEN RANKING = 4 THEN TVDL ELSE 0 END) AS TVDL04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN TVDL ELSE 0 END) AS TVDL05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN TVDL ELSE 0 END) AS TVDL99*/

	
	FROM WORK.&STATE._RATE_DRIVER02
	GROUP BY 1
;QUIT;

PROC SQL;
CREATE TABLE WORK.&state._Rate_Violation03 AS
SELECT
		 RateDriverLinkId
		,COUNT(RATEVIOLATIONID) AS Tot_Violation
		,SUM(AtFault) AS Tot_AtFault

		,MAX(CASE WHEN RANKING = 1 THEN RateViolationId ELSE 0 END) AS RateViolationId01
		,MAX(CASE WHEN RANKING = 2 THEN RateViolationId ELSE 0 END) AS RateViolationId02
		,MAX(CASE WHEN RANKING = 3 THEN RateViolationId ELSE 0 END) AS RateViolationId03
/*		,MAX(CASE WHEN RANKING = 4 THEN RateViolationId ELSE 0 END) AS RateViolationId04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN RateViolationId ELSE 0 END) AS RateViolationId05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN RateViolationId ELSE 0 END) AS RateViolationId99*/

		,MAX(CASE WHEN RANKING = 1 THEN AtFault ELSE 0 END) AS AtFault01
		,MAX(CASE WHEN RANKING = 2 THEN AtFault ELSE 0 END) AS AtFault02
		,MAX(CASE WHEN RANKING = 3 THEN AtFault ELSE 0 END) AS AtFault03
/*		,MAX(CASE WHEN RANKING = 4 THEN AtFault ELSE 0 END) AS AtFault04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN AtFault ELSE 0 END) AS AtFault05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN AtFault ELSE 0 END) AS AtFault99*/

		,SUM(Convicted) AS Tot_Convicted
		,MAX(CASE WHEN RANKING = 1 THEN Convicted ELSE 0 END) AS Convicted01
		,MAX(CASE WHEN RANKING = 2 THEN Convicted ELSE 0 END) AS Convicted02
		,MAX(CASE WHEN RANKING = 3 THEN Convicted ELSE 0 END) AS Convicted03
/*		,MAX(CASE WHEN RANKING = 4 THEN Convicted ELSE 0 END) AS Convicted04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN Convicted ELSE 0 END) AS Convicted05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN Convicted ELSE 0 END) AS Convicted99*/

		,MAX(CASE WHEN RANKING = 1 THEN ViolCode ELSE 0 END) AS ViolCode01
		,MAX(CASE WHEN RANKING = 2 THEN ViolCode ELSE 0 END) AS ViolCode02
		,MAX(CASE WHEN RANKING = 3 THEN ViolCode ELSE 0 END) AS ViolCode03
/*		,MAX(CASE WHEN RANKING = 4 THEN ViolCode ELSE 0 END) AS ViolCode04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN ViolCode ELSE 0 END) AS ViolCode05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN ViolCode ELSE 0 END) AS ViolCode99*/

		,MAX(CASE WHEN RANKING = 1 THEN ViolDate ELSE 0 END) AS ViolDate01
		,MAX(CASE WHEN RANKING = 2 THEN ViolDate ELSE 0 END) AS ViolDate02
		,MAX(CASE WHEN RANKING = 3 THEN ViolDate ELSE 0 END) AS ViolDate03
/*		,MAX(CASE WHEN RANKING = 4 THEN ViolDate ELSE 0 END) AS ViolDate04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN ViolDate ELSE 0 END) AS ViolDate05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN ViolDate ELSE 0 END) AS ViolDate99*/

		,MAX(CASE WHEN RANKING = 1 THEN ViolDate ELSE 0 END) AS ViolDate01
		,MAX(CASE WHEN RANKING = 2 THEN ViolDate ELSE 0 END) AS ViolDate02
		,MAX(CASE WHEN RANKING = 3 THEN ViolDate ELSE 0 END) AS ViolDate03
/*		,MAX(CASE WHEN RANKING = 4 THEN ViolDate ELSE 0 END) AS ViolDate04*/
/*		,MAX(CASE WHEN RANKING = 5 THEN ViolDate ELSE 0 END) AS ViolDate05*/
/*		,MAX(CASE WHEN RANKING > 5 THEN ViolDate ELSE 0 END) AS ViolDate99*/

		,MAX(CASE WHEN BI_PTS_1 > 0 THEN ViolDate ELSE 0 END) AS Most_Recent_ViolDate format=DATE9.

FROM WORK.&state._Rate_Violation02
GROUP BY 1
;QUIT;


PROC SQL;
	CREATE TABLE &state._Rate_Car03 AS
		SELECT
			 RateLinkID
			,MAX(CASE WHEN RANKING = 1 THEN RateVehicleId ELSE 0 END) AS RateVehicleId01
			,MAX(CASE WHEN RANKING = 2 THEN RateVehicleId ELSE 0 END) AS RateVehicleId02
			,MAX(CASE WHEN RANKING = 3 THEN RateVehicleId ELSE 0 END) AS RateVehicleId03
/*			,MAX(CASE WHEN RANKING = 4 THEN RateVehicleId ELSE 0 END) AS RateVehicleId04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN RateVehicleId ELSE 0 END) AS RateVehicleId05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN RateVehicleId ELSE 0 END) AS RateVehicleId99*/

			,COUNT(RateVehicleID) as VEH_CNT
			,MAX(CoSym) AS CoSym
			,MAX(CoTerr) AS CoTerr
			,SUM(LiabBIPremium*Term_Adj_Factor) AS LiabBIPremium
			,SUM(LiabPDPremium*Term_Adj_Factor) AS LiabPDPremium
			,SUM(MedPayPremium*Term_Adj_Factor) AS MedPayPremium
			,SUM(PIPPremium*Term_Adj_Factor) AS PIPPremium
			,SUM(RentalPremium*Term_Adj_Factor) AS RentalPremium
			,SUM(TowingPremium*Term_Adj_Factor) AS TowingPremium
			,SUM(UIMBIPremium*Term_Adj_Factor) AS UIMBIPremium
			,SUM(UIMPDPremium*Term_Adj_Factor) AS UIMPDPremium
			,SUM(UninsBIPremium*Term_Adj_Factor) AS UninsBIPremium
			,SUM(UninsPDPremium*Term_Adj_Factor) AS UninsPDPremium
			,SUM(CompPremium*Term_Adj_Factor) AS CompPremium
			,SUM(CollPremium*Term_Adj_Factor) AS CollPremium

			,MAX(CASE WHEN RANKING = 1 AND LiabBIPremium > 0 THEN 1 ELSE 0 END) AS LiabBIPremium_COV_IND01
			,MAX(CASE WHEN RANKING = 1 AND LiabPDPremium > 0 THEN 1 ELSE 0 END) AS LiabPDPremium_COV_IND01
			,MAX(CASE WHEN RANKING = 1 AND MedPayPremium > 0 THEN 1 ELSE 0 END) AS MedPayPremium_COV_IND01
			,MAX(CASE WHEN RANKING = 1 AND PIPPremium > 0 THEN 1 ELSE 0 END) AS PIPPremium_COV_IND01
			,MAX(CASE WHEN RANKING = 1 AND RentalPremium > 0 THEN 1 ELSE 0 END) AS RentalPremium_COV_IND01
			,MAX(CASE WHEN RANKING = 1 AND TowingPremium > 0 THEN 1 ELSE 0 END) AS TowingPremium_COV_IND01
			,MAX(CASE WHEN RANKING = 1 AND UIMBIPremium > 0 THEN 1 ELSE 0 END) AS UIMBIPremium_COV_IND01
			,MAX(CASE WHEN RANKING = 1 AND UIMPDPremium > 0 THEN 1 ELSE 0 END) AS UIMPDPremium_COV_IND01
			,MAX(CASE WHEN RANKING = 1 AND UninsBIPremium > 0 THEN 1 ELSE 0 END) AS UninsBIPremium_COV_IND01
			,MAX(CASE WHEN RANKING = 1 AND UninsPDPremium > 0 THEN 1 ELSE 0 END) AS UninsPDPremium_COV_IND01
			,MAX(CASE WHEN RANKING = 1 AND CompPremium > 0 THEN 1 ELSE 0 END) AS CompPremium_COV_IND01
			,MAX(CASE WHEN RANKING = 1 AND CollPremium > 0 THEN 1 ELSE 0 END) AS CollPremium_COV_IND01


			,MAX(CASE WHEN RANKING = 2 AND LiabBIPremium > 0 THEN 1 ELSE 0 END) AS LiabBIPremium_COV_IND02
			,MAX(CASE WHEN RANKING = 2 AND LiabPDPremium > 0 THEN 1 ELSE 0 END) AS LiabPDPremium_COV_IND02
			,MAX(CASE WHEN RANKING = 2 AND MedPayPremium > 0 THEN 1 ELSE 0 END) AS MedPayPremium_COV_IND02
			,MAX(CASE WHEN RANKING = 2 AND PIPPremium > 0 THEN 1 ELSE 0 END) AS PIPPremium_COV_IND02
			,MAX(CASE WHEN RANKING = 2 AND RentalPremium > 0 THEN 1 ELSE 0 END) AS RentalPremium_COV_IND02
			,MAX(CASE WHEN RANKING = 2 AND TowingPremium > 0 THEN 1 ELSE 0 END) AS TowingPremium_COV_IND02
			,MAX(CASE WHEN RANKING = 2 AND UIMBIPremium > 0 THEN 1 ELSE 0 END) AS UIMBIPremium_COV_IND02
			,MAX(CASE WHEN RANKING = 2 AND UIMPDPremium > 0 THEN 1 ELSE 0 END) AS UIMPDPremium_COV_IND02
			,MAX(CASE WHEN RANKING = 2 AND UninsBIPremium > 0 THEN 1 ELSE 0 END) AS UninsBIPremium_COV_IND02
			,MAX(CASE WHEN RANKING = 2 AND UninsPDPremium > 0 THEN 1 ELSE 0 END) AS UninsPDPremium_COV_IND02
			,MAX(CASE WHEN RANKING = 2 AND CompPremium > 0 THEN 1 ELSE 0 END) AS CompPremium_COV_IND02
			,MAX(CASE WHEN RANKING = 2 AND CollPremium > 0 THEN 1 ELSE 0 END) AS CollPremium_COV_IND02


			,MAX(CASE WHEN RANKING = 1 THEN CoLiabLimits1 ELSE 0 END) AS CoLiabLimits101
			,MAX(CASE WHEN RANKING = 2 THEN CoLiabLimits1 ELSE 0 END) AS CoLiabLimits102
			,MAX(CASE WHEN RANKING = 3 THEN CoLiabLimits1 ELSE 0 END) AS CoLiabLimits103
/*			,MAX(CASE WHEN RANKING = 4 THEN CoLiabLimits1 ELSE 0 END) AS CoLiabLimits104*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoLiabLimits1 ELSE 0 END) AS CoLiabLimits105*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoLiabLimits1 ELSE 0 END) AS CoLiabLimits199*/

			,MAX(CASE WHEN RANKING = 1 THEN CoLiabLimits2 ELSE 0 END) AS CoLiabLimits201
			,MAX(CASE WHEN RANKING = 2 THEN CoLiabLimits2 ELSE 0 END) AS CoLiabLimits202
			,MAX(CASE WHEN RANKING = 3 THEN CoLiabLimits2 ELSE 0 END) AS CoLiabLimits203
/*			,MAX(CASE WHEN RANKING = 4 THEN CoLiabLimits2 ELSE 0 END) AS CoLiabLimits204*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoLiabLimits2 ELSE 0 END) AS CoLiabLimits205*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoLiabLimits2 ELSE 0 END) AS CoLiabLimits299*/

			,MAX(CASE WHEN RANKING = 1 THEN CoLiabLimits3 ELSE 0 END) AS CoLiabLimits301
			,MAX(CASE WHEN RANKING = 2 THEN CoLiabLimits3 ELSE 0 END) AS CoLiabLimits302
			,MAX(CASE WHEN RANKING = 3 THEN CoLiabLimits3 ELSE 0 END) AS CoLiabLimits303
/*			,MAX(CASE WHEN RANKING = 4 THEN CoLiabLimits3 ELSE 0 END) AS CoLiabLimits304*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoLiabLimits3 ELSE 0 END) AS CoLiabLimits305*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoLiabLimits3 ELSE 0 END) AS CoLiabLimits399*/

			,MAX(CASE WHEN RANKING = 1 THEN CoCollDed ELSE 0 END) AS CoCollDed01
			,MAX(CASE WHEN RANKING = 2 THEN CoCollDed ELSE 0 END) AS CoCollDed02
			,MAX(CASE WHEN RANKING = 3 THEN CoCollDed ELSE 0 END) AS CoCollDed03
/*			,MAX(CASE WHEN RANKING = 4 THEN CoCollDed ELSE 0 END) AS CoCollDed04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoCollDed ELSE 0 END) AS CoCollDed05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoCollDed ELSE 0 END) AS CoCollDed99*/

			,MAX(CASE WHEN RANKING = 1 THEN CoCompDed ELSE 0 END) AS CoCompDed01
			,MAX(CASE WHEN RANKING = 2 THEN CoCompDed ELSE 0 END) AS CoCompDed02
			,MAX(CASE WHEN RANKING = 3 THEN CoCompDed ELSE 0 END) AS CoCompDed03
/*			,MAX(CASE WHEN RANKING = 4 THEN CoCompDed ELSE 0 END) AS CoCompDed04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoCompDed ELSE 0 END) AS CoCompDed05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoCompDed ELSE 0 END) AS CoCompDed99*/

			,MAX(CASE WHEN RANKING = 1 THEN CoPIPLimit ELSE 0 END) AS CoPIPLimit01
			,MAX(CASE WHEN RANKING = 2 THEN CoPIPLimit ELSE 0 END) AS CoPIPLimit02
			,MAX(CASE WHEN RANKING = 3 THEN CoPIPLimit ELSE 0 END) AS CoPIPLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN CoPIPLimit ELSE 0 END) AS CoPIPLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoPIPLimit ELSE 0 END) AS CoPIPLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoPIPLimit ELSE 0 END) AS CoPIPLimit99*/

			,MAX(CASE WHEN RANKING = 1 THEN CoMedPayLimit ELSE 0 END) AS CoMedPayLimit01
			,MAX(CASE WHEN RANKING = 2 THEN CoMedPayLimit ELSE 0 END) AS CoMedPayLimit02
			,MAX(CASE WHEN RANKING = 3 THEN CoMedPayLimit ELSE 0 END) AS CoMedPayLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN CoMedPayLimit ELSE 0 END) AS CoMedPayLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoMedPayLimit ELSE 0 END) AS CoMedPayLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoMedPayLimit ELSE 0 END) AS CoMedPayLimit99*/

			,MAX(CASE WHEN RANKING = 1 THEN CoUIMBILimits1 ELSE 0 END) AS CoUIMBILimits101
			,MAX(CASE WHEN RANKING = 2 THEN CoUIMBILimits1 ELSE 0 END) AS CoUIMBILimits102
			,MAX(CASE WHEN RANKING = 3 THEN CoUIMBILimits1 ELSE 0 END) AS CoUIMBILimits103
/*			,MAX(CASE WHEN RANKING = 4 THEN CoUIMBILimits1 ELSE 0 END) AS CoUIMBILimits104*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoUIMBILimits1 ELSE 0 END) AS CoUIMBILimits105*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoUIMBILimits1 ELSE 0 END) AS CoUIMBILimits199*/

			,MAX(CASE WHEN RANKING = 1 THEN CoUIMBILimits2 ELSE 0 END) AS CoUIMBILimits201
			,MAX(CASE WHEN RANKING = 2 THEN CoUIMBILimits2 ELSE 0 END) AS CoUIMBILimits202
			,MAX(CASE WHEN RANKING = 3 THEN CoUIMBILimits2 ELSE 0 END) AS CoUIMBILimits203
/*			,MAX(CASE WHEN RANKING = 4 THEN CoUIMBILimits2 ELSE 0 END) AS CoUIMBILimits204*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoUIMBILimits2 ELSE 0 END) AS CoUIMBILimits205*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoUIMBILimits2 ELSE 0 END) AS CoUIMBILimits299*/

			,MAX(CASE WHEN RANKING = 1 THEN CoUIMPDLimit ELSE 0 END) AS CoUIMPDLimit01
			,MAX(CASE WHEN RANKING = 2 THEN CoUIMPDLimit ELSE 0 END) AS CoUIMPDLimit02
			,MAX(CASE WHEN RANKING = 3 THEN CoUIMPDLimit ELSE 0 END) AS CoUIMPDLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN CoUIMPDLimit ELSE 0 END) AS CoUIMPDLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoUIMPDLimit ELSE 0 END) AS CoUIMPDLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoUIMPDLimit ELSE 0 END) AS CoUIMPDLimit99*/

			,MAX(CASE WHEN RANKING = 1 THEN CoUninsBILimits1 ELSE 0 END) AS CoUninsBILimits101
			,MAX(CASE WHEN RANKING = 2 THEN CoUninsBILimits1 ELSE 0 END) AS CoUninsBILimits102
			,MAX(CASE WHEN RANKING = 3 THEN CoUninsBILimits1 ELSE 0 END) AS CoUninsBILimits103
/*			,MAX(CASE WHEN RANKING = 4 THEN CoUninsBILimits1 ELSE 0 END) AS CoUninsBILimits104*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoUninsBILimits1 ELSE 0 END) AS CoUninsBILimits105*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoUninsBILimits1 ELSE 0 END) AS CoUninsBILimits199*/

			,MAX(CASE WHEN RANKING = 1 THEN CoUninsBILimits2 ELSE 0 END) AS CoUninsBILimits201
			,MAX(CASE WHEN RANKING = 2 THEN CoUninsBILimits2 ELSE 0 END) AS CoUninsBILimits202
			,MAX(CASE WHEN RANKING = 3 THEN CoUninsBILimits2 ELSE 0 END) AS CoUninsBILimits203
/*			,MAX(CASE WHEN RANKING = 4 THEN CoUninsBILimits2 ELSE 0 END) AS CoUninsBILimits204*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoUninsBILimits2 ELSE 0 END) AS CoUninsBILimits205*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoUninsBILimits2 ELSE 0 END) AS CoUninsBILimits299*/

			,MAX(CASE WHEN RANKING = 1 THEN CoUninsPDLimit ELSE 0 END) AS CoUninsPDLimit01
			,MAX(CASE WHEN RANKING = 2 THEN CoUninsPDLimit ELSE 0 END) AS CoUninsPDLimit02
			,MAX(CASE WHEN RANKING = 3 THEN CoUninsPDLimit ELSE 0 END) AS CoUninsPDLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN CoUninsPDLimit ELSE 0 END) AS CoUninsPDLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoUninsPDLimit ELSE 0 END) AS CoUninsPDLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoUninsPDLimit ELSE 0 END) AS CoUninsPDLimit99*/

			,MAX(CASE WHEN RANKING = 1 THEN CollDed ELSE 0 END) AS CollDed01
			,MAX(CASE WHEN RANKING = 2 THEN CollDed ELSE 0 END) AS CollDed02
			,MAX(CASE WHEN RANKING = 3 THEN CollDed ELSE 0 END) AS CollDed03
/*			,MAX(CASE WHEN RANKING = 4 THEN CollDed ELSE 0 END) AS CollDed04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CollDed ELSE 0 END) AS CollDed05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CollDed ELSE 0 END) AS CollDed99*/

			,MAX(CASE WHEN RANKING = 1 THEN CompDed ELSE 0 END) AS CompDed01
			,MAX(CASE WHEN RANKING = 2 THEN CompDed ELSE 0 END) AS CompDed02
			,MAX(CASE WHEN RANKING = 3 THEN CompDed ELSE 0 END) AS CompDed03
/*			,MAX(CASE WHEN RANKING = 4 THEN CompDed ELSE 0 END) AS CompDed04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CompDed ELSE 0 END) AS CompDed05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CompDed ELSE 0 END) AS CompDed99*/

			,MAX(CASE WHEN RANKING = 1 THEN CoUninsPDDed ELSE 0 END) AS CoUninsPDDed01
			,MAX(CASE WHEN RANKING = 2 THEN CoUninsPDDed ELSE 0 END) AS CoUninsPDDed02
			,MAX(CASE WHEN RANKING = 3 THEN CoUninsPDDed ELSE 0 END) AS CoUninsPDDed03
/*			,MAX(CASE WHEN RANKING = 4 THEN CoUninsPDDed ELSE 0 END) AS CoUninsPDDed04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoUninsPDDed ELSE 0 END) AS CoUninsPDDed05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoUninsPDDed ELSE 0 END) AS CoUninsPDDed99*/

			,MAX(CASE WHEN RANKING = 1 THEN CoTowingLimit ELSE 0 END) AS CoTowingLimit01
			,MAX(CASE WHEN RANKING = 2 THEN CoTowingLimit ELSE 0 END) AS CoTowingLimit02
			,MAX(CASE WHEN RANKING = 3 THEN CoTowingLimit ELSE 0 END) AS CoTowingLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN CoTowingLimit ELSE 0 END) AS CoTowingLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoTowingLimit ELSE 0 END) AS CoTowingLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoTowingLimit ELSE 0 END) AS CoTowingLimit99*/

			,MAX(CASE WHEN RANKING = 1 THEN CoRentalLimit ELSE 0 END) AS CoRentalLimit01
			,MAX(CASE WHEN RANKING = 2 THEN CoRentalLimit ELSE 0 END) AS CoRentalLimit02
			,MAX(CASE WHEN RANKING = 3 THEN CoRentalLimit ELSE 0 END) AS CoRentalLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN CoRentalLimit ELSE 0 END) AS CoRentalLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoRentalLimit ELSE 0 END) AS CoRentalLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoRentalLimit ELSE 0 END) AS CoRentalLimit99*/

			,MAX(CASE WHEN RANKING = 1 THEN PIPLimit ELSE 0 END) AS PIPLimit01
			,MAX(CASE WHEN RANKING = 2 THEN PIPLimit ELSE 0 END) AS PIPLimit02
			,MAX(CASE WHEN RANKING = 3 THEN PIPLimit ELSE 0 END) AS PIPLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN PIPLimit ELSE 0 END) AS PIPLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN PIPLimit ELSE 0 END) AS PIPLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN PIPLimit ELSE 0 END) AS PIPLimit99*/

			

/*			,CoTowingLimit*/
/*			,CoUIMPDLimit*/
/*			,CoUninsBILimits1*/
/*			,CoUninsBILimits2*/
/*			,CoUninsPDLimit*/
/*			,CoRentalLimit*/
/*			,CoUninsPDDed*/

/*			,IncludedCoverages*/

			,MAX(CASE WHEN RANKING = 1 THEN VIN ELSE "" END) AS VIN01
			,MAX(CASE WHEN RANKING = 2 THEN VIN ELSE "" END) AS VIN02
			,MAX(CASE WHEN RANKING = 3 THEN VIN ELSE "" END) AS VIN03
/*			,MAX(CASE WHEN RANKING = 4 THEN VIN ELSE "" END) AS VIN04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN VIN ELSE "" END) AS VIN05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN VIN ELSE "" END) AS VIN99*/

			,MAX(CASE WHEN RANKING = 1 THEN MedPayLimit ELSE 0 END) AS MedPayLimit01
			,MAX(CASE WHEN RANKING = 2 THEN MedPayLimit ELSE 0 END) AS MedPayLimit02
			,MAX(CASE WHEN RANKING = 3 THEN MedPayLimit ELSE 0 END) AS MedPayLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN MedPayLimit ELSE 0 END) AS MedPayLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN MedPayLimit ELSE 0 END) AS MedPayLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN MedPayLimit ELSE 0 END) AS MedPayLimit99*/

			,MAX(CASE WHEN RANKING = 1 THEN RentalLimit ELSE 0 END) AS RentalLimit01
			,MAX(CASE WHEN RANKING = 2 THEN RentalLimit ELSE 0 END) AS RentalLimit02
			,MAX(CASE WHEN RANKING = 3 THEN RentalLimit ELSE 0 END) AS RentalLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN RentalLimit ELSE 0 END) AS RentalLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN RentalLimit ELSE 0 END) AS RentalLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN RentalLimit ELSE 0 END) AS RentalLimit99*/

			,MAX(CASE WHEN RANKING = 1 THEN TowingLimit ELSE 0 END) AS TowingLimit01
			,MAX(CASE WHEN RANKING = 2 THEN TowingLimit ELSE 0 END) AS TowingLimit02
			,MAX(CASE WHEN RANKING = 3 THEN TowingLimit ELSE 0 END) AS TowingLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN TowingLimit ELSE 0 END) AS TowingLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN TowingLimit ELSE 0 END) AS TowingLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN TowingLimit ELSE 0 END) AS TowingLimit99*/

			,MAX(CASE WHEN RANKING = 1 THEN UIMPDLimit ELSE 0 END) AS UIMPDLimit01
			,MAX(CASE WHEN RANKING = 2 THEN UIMPDLimit ELSE 0 END) AS UIMPDLimit02
			,MAX(CASE WHEN RANKING = 3 THEN UIMPDLimit ELSE 0 END) AS UIMPDLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN UIMPDLimit ELSE 0 END) AS UIMPDLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN UIMPDLimit ELSE 0 END) AS UIMPDLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN UIMPDLimit ELSE 0 END) AS UIMPDLimit99*/

			,MAX(CASE WHEN RANKING = 1 THEN UninsPDLimit ELSE 0 END) AS UninsPDLimit01
			,MAX(CASE WHEN RANKING = 2 THEN UninsPDLimit ELSE 0 END) AS UninsPDLimit02
			,MAX(CASE WHEN RANKING = 3 THEN UninsPDLimit ELSE 0 END) AS UninsPDLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN UninsPDLimit ELSE 0 END) AS UninsPDLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN UninsPDLimit ELSE 0 END) AS UninsPDLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN UninsPDLimit ELSE 0 END) AS UninsPDLimit99*/


			,MAX(CASE WHEN RANKING = 1 THEN UninsPDLimit ELSE 0 END) AS UninsPDLimit01
			,MAX(CASE WHEN RANKING = 2 THEN UninsPDLimit ELSE 0 END) AS UninsPDLimit02
			,MAX(CASE WHEN RANKING = 3 THEN UninsPDLimit ELSE 0 END) AS UninsPDLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN UninsPDLimit ELSE 0 END) AS UninsPDLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN UninsPDLimit ELSE 0 END) AS UninsPDLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN UninsPDLimit ELSE 0 END) AS UninsPDLimit99*/
		

/*			,AnnualMiles*/
/*			,County*/
/*			,Miles*/
/*			,Odometer*/
/*			,PercentToWork*/
/*			,Usage*/
/*			,ZipCode*/
/*			,Garaged*/
/*			,GaragingZipCpde*/
/*			,LeasedVehicle*/

			,MAX(CASE WHEN RANKING = 1 THEN LiabLimits1 ELSE 0 END) AS LiabLimits101
			,MAX(CASE WHEN RANKING = 2 THEN LiabLimits1 ELSE 0 END) AS LiabLimits102
			,MAX(CASE WHEN RANKING = 3 THEN LiabLimits1 ELSE 0 END) AS LiabLimits103
/*			,MAX(CASE WHEN RANKING = 4 THEN LiabLimits1 ELSE 0 END) AS LiabLimits104*/
/*			,MAX(CASE WHEN RANKING = 5 THEN LiabLimits1 ELSE 0 END) AS LiabLimits105*/
/*			,MAX(CASE WHEN RANKING > 5 THEN LiabLimits1 ELSE 0 END) AS LiabLimits199*/

			,MAX(CASE WHEN RANKING = 1 THEN LiabLimits2 ELSE 0 END) AS LiabLimits201
			,MAX(CASE WHEN RANKING = 2 THEN LiabLimits2 ELSE 0 END) AS LiabLimits202
			,MAX(CASE WHEN RANKING = 3 THEN LiabLimits2 ELSE 0 END) AS LiabLimits203
/*			,MAX(CASE WHEN RANKING = 4 THEN LiabLimits2 ELSE 0 END) AS LiabLimits204*/
/*			,MAX(CASE WHEN RANKING = 5 THEN LiabLimits2 ELSE 0 END) AS LiabLimits205*/
/*			,MAX(CASE WHEN RANKING > 5 THEN LiabLimits2 ELSE 0 END) AS LiabLimits299*/

			,MAX(CASE WHEN RANKING = 1 THEN LiabLimits3 ELSE 0 END) AS LiabLimits301
			,MAX(CASE WHEN RANKING = 2 THEN LiabLimits3 ELSE 0 END) AS LiabLimits302
			,MAX(CASE WHEN RANKING = 3 THEN LiabLimits3 ELSE 0 END) AS LiabLimits303
/*			,MAX(CASE WHEN RANKING = 4 THEN LiabLimits3 ELSE 0 END) AS LiabLimits304*/
/*			,MAX(CASE WHEN RANKING = 5 THEN LiabLimits3 ELSE 0 END) AS LiabLimits305*/
/*			,MAX(CASE WHEN RANKING > 5 THEN LiabLimits3 ELSE 0 END) AS LiabLimits399*/

			,MAX(CASE WHEN RANKING = 1 THEN UninsBILimits1 ELSE 0 END) AS UninsBILimits101
			,MAX(CASE WHEN RANKING = 2 THEN UninsBILimits1 ELSE 0 END) AS UninsBILimits102
			,MAX(CASE WHEN RANKING = 3 THEN UninsBILimits1 ELSE 0 END) AS UninsBILimits103
/*			,MAX(CASE WHEN RANKING = 4 THEN UninsBILimits1 ELSE 0 END) AS UninsBILimits104*/
/*			,MAX(CASE WHEN RANKING = 5 THEN UninsBILimits1 ELSE 0 END) AS UninsBILimits105*/
/*			,MAX(CASE WHEN RANKING > 5 THEN UninsBILimits1 ELSE 0 END) AS UninsBILimits199*/

			,MAX(CASE WHEN RANKING = 1 THEN UninsBILimits2 ELSE 0 END) AS UninsBILimits201
			,MAX(CASE WHEN RANKING = 2 THEN UninsBILimits2 ELSE 0 END) AS UninsBILimits202
			,MAX(CASE WHEN RANKING = 3 THEN UninsBILimits2 ELSE 0 END) AS UninsBILimits203
/*			,MAX(CASE WHEN RANKING = 4 THEN UninsBILimits2 ELSE 0 END) AS UninsBILimits204*/
/*			,MAX(CASE WHEN RANKING = 5 THEN UninsBILimits2 ELSE 0 END) AS UninsBILimits205*/
/*			,MAX(CASE WHEN RANKING > 5 THEN UninsBILimits2 ELSE 0 END) AS UninsBILimits299*/

			,MAX(CASE WHEN RANKING = 1 THEN UIMBILimits1 ELSE 0 END) AS UIMBILimits101
			,MAX(CASE WHEN RANKING = 2 THEN UIMBILimits1 ELSE 0 END) AS UIMBILimits102
			,MAX(CASE WHEN RANKING = 3 THEN UIMBILimits1 ELSE 0 END) AS UIMBILimits103
/*			,MAX(CASE WHEN RANKING = 4 THEN UIMBILimits1 ELSE 0 END) AS UIMBILimits104*/
/*			,MAX(CASE WHEN RANKING = 5 THEN UIMBILimits1 ELSE 0 END) AS UIMBILimits105*/
/*			,MAX(CASE WHEN RANKING > 5 THEN UIMBILimits1 ELSE 0 END) AS UIMBILimits199*/

			,MAX(CASE WHEN RANKING = 1 THEN UIMBILimits2 ELSE 0 END) AS UIMBILimits201
			,MAX(CASE WHEN RANKING = 2 THEN UIMBILimits2 ELSE 0 END) AS UIMBILimits202
			,MAX(CASE WHEN RANKING = 3 THEN UIMBILimits2 ELSE 0 END) AS UIMBILimits203
/*			,MAX(CASE WHEN RANKING = 4 THEN UIMBILimits2 ELSE 0 END) AS UIMBILimits204*/
/*			,MAX(CASE WHEN RANKING = 5 THEN UIMBILimits2 ELSE 0 END) AS UIMBILimits205*/
/*			,MAX(CASE WHEN RANKING > 5 THEN UIMBILimits2 ELSE 0 END) AS UIMBILimits299*/

/*			,PrimaryOperator*/

			,MAX(CASE WHEN RANKING = 1 THEN Year ELSE 0 END) AS Year01
			,MAX(CASE WHEN RANKING = 2 THEN Year ELSE 0 END) AS Year02
			,MAX(CASE WHEN RANKING = 3 THEN Year ELSE 0 END) AS Year03
/*			,MAX(CASE WHEN RANKING = 4 THEN Year ELSE 0 END) AS Year04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN Year ELSE 0 END) AS Year05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN Year ELSE 0 END) AS Year99*/

			,MAX(CASE WHEN RANKING = 1 THEN Maker ELSE "" END) AS Maker01
			,MAX(CASE WHEN RANKING = 2 THEN Maker ELSE "" END) AS Maker02
			,MAX(CASE WHEN RANKING = 3 THEN Maker ELSE "" END) AS Maker03
/*			,MAX(CASE WHEN RANKING = 4 THEN Maker ELSE "" END) AS Maker04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN Maker ELSE "" END) AS Maker05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN Maker ELSE "" END) AS Maker99*/

			,MAX(CASE WHEN RANKING = 1 THEN Model ELSE "" END) AS Model01
			,MAX(CASE WHEN RANKING = 2 THEN Model ELSE "" END) AS Model02
			,MAX(CASE WHEN RANKING = 3 THEN Model ELSE "" END) AS Model03
/*			,MAX(CASE WHEN RANKING = 4 THEN Model ELSE "" END) AS Model04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN Model ELSE "" END) AS Model05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN Model ELSE "" END) AS Model99*/

			,MAX(CASE WHEN RANKING = 1 THEN ACV ELSE 0 END) AS ACV01
			,MAX(CASE WHEN RANKING = 2 THEN ACV ELSE 0 END) AS ACV02
			,MAX(CASE WHEN RANKING = 3 THEN ACV ELSE 0 END) AS ACV03
/*			,MAX(CASE WHEN RANKING = 4 THEN ACV ELSE 0 END) AS ACV04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN ACV ELSE 0 END) AS ACV05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN ACV ELSE 0 END) AS ACV99*/

			,MAX(CASE WHEN RANKING = 1 THEN AccDeathPremium ELSE 0 END) AS AccDeathPremium01
			,MAX(CASE WHEN RANKING = 2 THEN AccDeathPremium ELSE 0 END) AS AccDeathPremium02
			,MAX(CASE WHEN RANKING = 3 THEN AccDeathPremium ELSE 0 END) AS AccDeathPremium03
/*			,MAX(CASE WHEN RANKING = 4 THEN AccDeathPremium ELSE 0 END) AS AccDeathPremium04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN AccDeathPremium ELSE 0 END) AS AccDeathPremium05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN AccDeathPremium ELSE 0 END) AS AccDeathPremium99*/

			,MAX(CASE WHEN RANKING = 1 THEN CoAccDeathLimit ELSE 0 END) AS CoAccDeathLimit01
			,MAX(CASE WHEN RANKING = 2 THEN CoAccDeathLimit ELSE 0 END) AS CoAccDeathLimit02
			,MAX(CASE WHEN RANKING = 3 THEN CoAccDeathLimit ELSE 0 END) AS CoAccDeathLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN CoAccDeathLimit ELSE 0 END) AS CoAccDeathLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoAccDeathLimit ELSE 0 END) AS CoAccDeathLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoAccDeathLimit ELSE 0 END) AS CoAccDeathLimit99*/

			
			,MAX(CASE WHEN RANKING = 1 THEN CoCustomEquipLimit ELSE 0 END) AS CoCustomEquipLimit01
			,MAX(CASE WHEN RANKING = 2 THEN CoCustomEquipLimit ELSE 0 END) AS CoCustomEquipLimit02
			,MAX(CASE WHEN RANKING = 3 THEN CoCustomEquipLimit ELSE 0 END) AS CoCustomEquipLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN CoCustomEquipLimit ELSE 0 END) AS CoCustomEquipLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoCustomEquipLimit ELSE 0 END) AS CoCustomEquipLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoCustomEquipLimit ELSE 0 END) AS CoCustomEquipLimit99*/

			,MAX(CASE WHEN RANKING = 1 THEN CoExtraMedLimit ELSE 0 END) AS CoExtraMedLimit01
			,MAX(CASE WHEN RANKING = 2 THEN CoExtraMedLimit ELSE 0 END) AS CoExtraMedLimit02
			,MAX(CASE WHEN RANKING = 3 THEN CoExtraMedLimit ELSE 0 END) AS CoExtraMedLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN CoExtraMedLimit ELSE 0 END) AS CoExtraMedLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoExtraMedLimit ELSE 0 END) AS CoExtraMedLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoExtraMedLimit ELSE 0 END) AS CoExtraMedLimit99*/


			,MAX(CASE WHEN RANKING = 1 THEN CoSafetyGlass ELSE 0 END) AS CoSafetyGlass01
			,MAX(CASE WHEN RANKING = 2 THEN CoSafetyGlass ELSE 0 END) AS CoSafetyGlass02
			,MAX(CASE WHEN RANKING = 3 THEN CoSafetyGlass ELSE 0 END) AS CoSafetyGlass03
/*			,MAX(CASE WHEN RANKING = 4 THEN CoSafetyGlass ELSE 0 END) AS CoSafetyGlass04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoSafetyGlass ELSE 0 END) AS CoSafetyGlass05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoSafetyGlass ELSE 0 END) AS CoSafetyGlass99*/

			,MAX(CASE WHEN RANKING = 1 THEN CoGapCoverage ELSE 0 END) AS CoGapCoverage01
			,MAX(CASE WHEN RANKING = 2 THEN CoGapCoverage ELSE 0 END) AS CoGapCoverage02
			,MAX(CASE WHEN RANKING = 3 THEN CoGapCoverage ELSE 0 END) AS CoGapCoverage03
/*			,MAX(CASE WHEN RANKING = 4 THEN CoGapCoverage ELSE 0 END) AS CoGapCoverage04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoGapCoverage ELSE 0 END) AS CoGapCoverage05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoGapCoverage ELSE 0 END) AS CoGapCoverage99*/

			,MAX(CASE WHEN RANKING = 1 THEN CoIncomeLossLimit ELSE 0 END) AS CoIncomeLossLimit01
			,MAX(CASE WHEN RANKING = 2 THEN CoIncomeLossLimit ELSE 0 END) AS CoIncomeLossLimit02
			,MAX(CASE WHEN RANKING = 3 THEN CoIncomeLossLimit ELSE 0 END) AS CoIncomeLossLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN CoIncomeLossLimit ELSE 0 END) AS CoIncomeLossLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoIncomeLossLimit ELSE 0 END) AS CoIncomeLossLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoIncomeLossLimit ELSE 0 END) AS CoIncomeLossLimit99*/

			,MAX(CASE WHEN RANKING = 1 THEN CoIncomeLossLimit2 ELSE 0 END) AS CoIncomeLossLimit201
			,MAX(CASE WHEN RANKING = 2 THEN CoIncomeLossLimit2 ELSE 0 END) AS CoIncomeLossLimit202
			,MAX(CASE WHEN RANKING = 3 THEN CoIncomeLossLimit2 ELSE 0 END) AS CoIncomeLossLimit203
/*			,MAX(CASE WHEN RANKING = 4 THEN CoIncomeLossLimit2 ELSE 0 END) AS CoIncomeLossLimit204*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CoIncomeLossLimit2 ELSE 0 END) AS CoIncomeLossLimit205*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CoIncomeLossLimit2 ELSE 0 END) AS CoIncomeLossLimit299*/


			,MAX(CASE WHEN RANKING = 1 THEN AccDeathPremium ELSE 0 END) AS AccDeathPremium01
			,MAX(CASE WHEN RANKING = 2 THEN AccDeathPremium ELSE 0 END) AS AccDeathPremium02
			,MAX(CASE WHEN RANKING = 3 THEN AccDeathPremium ELSE 0 END) AS AccDeathPremium03
/*			,MAX(CASE WHEN RANKING = 4 THEN AccDeathPremium ELSE 0 END) AS AccDeathPremium04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN AccDeathPremium ELSE 0 END) AS AccDeathPremium05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN AccDeathPremium ELSE 0 END) AS AccDeathPremium99*/

			,MAX(CASE WHEN RANKING = 1 THEN CustomEquipPremium ELSE 0 END) AS CustomEquipPremium01
			,MAX(CASE WHEN RANKING = 2 THEN CustomEquipPremium ELSE 0 END) AS CustomEquipPremium02
			,MAX(CASE WHEN RANKING = 3 THEN CustomEquipPremium ELSE 0 END) AS CustomEquipPremium03
/*			,MAX(CASE WHEN RANKING = 4 THEN CustomEquipPremium ELSE 0 END) AS CustomEquipPremium04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CustomEquipPremium ELSE 0 END) AS CustomEquipPremium05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CustomEquipPremium ELSE 0 END) AS CustomEquipPremium99*/

			,MAX(CASE WHEN RANKING = 1 THEN ExtraMedPremium ELSE 0 END) AS ExtraMedPremium01
			,MAX(CASE WHEN RANKING = 2 THEN ExtraMedPremium ELSE 0 END) AS ExtraMedPremium02
			,MAX(CASE WHEN RANKING = 3 THEN ExtraMedPremium ELSE 0 END) AS ExtraMedPremium03
/*			,MAX(CASE WHEN RANKING = 4 THEN ExtraMedPremium ELSE 0 END) AS ExtraMedPremium04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN ExtraMedPremium ELSE 0 END) AS ExtraMedPremium05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN ExtraMedPremium ELSE 0 END) AS ExtraMedPremium99*/

			,MAX(CASE WHEN RANKING = 1 THEN SafetyGlassPremium ELSE 0 END) AS SafetyGlassPremium01
			,MAX(CASE WHEN RANKING = 2 THEN SafetyGlassPremium ELSE 0 END) AS SafetyGlassPremium02
			,MAX(CASE WHEN RANKING = 3 THEN SafetyGlassPremium ELSE 0 END) AS SafetyGlassPremium03
/*			,MAX(CASE WHEN RANKING = 4 THEN SafetyGlassPremium ELSE 0 END) AS SafetyGlassPremium04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN SafetyGlassPremium ELSE 0 END) AS SafetyGlassPremium05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN SafetyGlassPremium ELSE 0 END) AS SafetyGlassPremium99*/

			,MAX(CASE WHEN RANKING = 1 THEN GapPremium ELSE 0 END) AS GapPremium01
			,MAX(CASE WHEN RANKING = 2 THEN GapPremium ELSE 0 END) AS GapPremium02
			,MAX(CASE WHEN RANKING = 3 THEN GapPremium ELSE 0 END) AS GapPremium03
/*			,MAX(CASE WHEN RANKING = 4 THEN GapPremium ELSE 0 END) AS GapPremium04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN GapPremium ELSE 0 END) AS GapPremium05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN GapPremium ELSE 0 END) AS GapPremium99*/

			,MAX(CASE WHEN RANKING = 1 THEN IncomeLossPremium ELSE 0 END) AS IncomeLossPremium01
			,MAX(CASE WHEN RANKING = 2 THEN IncomeLossPremium ELSE 0 END) AS IncomeLossPremium02
			,MAX(CASE WHEN RANKING = 3 THEN IncomeLossPremium ELSE 0 END) AS IncomeLossPremium03
/*			,MAX(CASE WHEN RANKING = 4 THEN IncomeLossPremium ELSE 0 END) AS IncomeLossPremium04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN IncomeLossPremium ELSE 0 END) AS IncomeLossPremium05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN IncomeLossPremium ELSE 0 END) AS IncomeLossPremium99*/


			,MAX(CASE WHEN RANKING = 1 THEN LegalExpensePremium ELSE 0 END) AS LegalExpensePremium01
			,MAX(CASE WHEN RANKING = 2 THEN LegalExpensePremium ELSE 0 END) AS LegalExpensePremium02
			,MAX(CASE WHEN RANKING = 3 THEN LegalExpensePremium ELSE 0 END) AS LegalExpensePremium03
/*			,MAX(CASE WHEN RANKING = 4 THEN LegalExpensePremium ELSE 0 END) AS LegalExpensePremium04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN LegalExpensePremium ELSE 0 END) AS LegalExpensePremium05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN LegalExpensePremium ELSE 0 END) AS LegalExpensePremium99*/

			,MAX(CASE WHEN RANKING = 1 THEN AccDeathLimit ELSE 0 END) AS AccDeathLimit01
			,MAX(CASE WHEN RANKING = 2 THEN AccDeathLimit ELSE 0 END) AS AccDeathLimit02
			,MAX(CASE WHEN RANKING = 3 THEN AccDeathLimit ELSE 0 END) AS AccDeathLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN AccDeathLimit ELSE 0 END) AS AccDeathLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN AccDeathLimit ELSE 0 END) AS AccDeathLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN AccDeathLimit ELSE 0 END) AS AccDeathLimit99*/


			,MAX(CASE WHEN RANKING = 1 THEN CustomEquipLimit ELSE 0 END) AS CustomEquipLimit01
			,MAX(CASE WHEN RANKING = 2 THEN CustomEquipLimit ELSE 0 END) AS CustomEquipLimit02
			,MAX(CASE WHEN RANKING = 3 THEN CustomEquipLimit ELSE 0 END) AS CustomEquipLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN CustomEquipLimit ELSE 0 END) AS CustomEquipLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN CustomEquipLimit ELSE 0 END) AS CustomEquipLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN CustomEquipLimit ELSE 0 END) AS CustomEquipLimit99*/

			,MAX(CASE WHEN RANKING = 1 THEN ExtraMedLimit ELSE 0 END) AS ExtraMedLimit01
			,MAX(CASE WHEN RANKING = 2 THEN ExtraMedLimit ELSE 0 END) AS ExtraMedLimit02
			,MAX(CASE WHEN RANKING = 3 THEN ExtraMedLimit ELSE 0 END) AS ExtraMedLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN ExtraMedLimit ELSE 0 END) AS ExtraMedLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN ExtraMedLimit ELSE 0 END) AS ExtraMedLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN ExtraMedLimit ELSE 0 END) AS ExtraMedLimit99*/

			,MAX(CASE WHEN RANKING = 1 THEN SafetyGlass ELSE 0 END) AS SafetyGlass01
			,MAX(CASE WHEN RANKING = 2 THEN SafetyGlass ELSE 0 END) AS SafetyGlass02
			,MAX(CASE WHEN RANKING = 3 THEN SafetyGlass ELSE 0 END) AS SafetyGlass03
/*			,MAX(CASE WHEN RANKING = 4 THEN SafetyGlass ELSE 0 END) AS SafetyGlass04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN SafetyGlass ELSE 0 END) AS SafetyGlass05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN SafetyGlass ELSE 0 END) AS SafetyGlass99*/

			,MAX(CASE WHEN RANKING = 1 THEN GapCoverage ELSE 0 END) AS GapCoverage01
			,MAX(CASE WHEN RANKING = 2 THEN GapCoverage ELSE 0 END) AS GapCoverage02
			,MAX(CASE WHEN RANKING = 3 THEN GapCoverage ELSE 0 END) AS GapCoverage03
/*			,MAX(CASE WHEN RANKING = 4 THEN GapCoverage ELSE 0 END) AS GapCoverage04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN GapCoverage ELSE 0 END) AS GapCoverage05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN GapCoverage ELSE 0 END) AS GapCoverage99*/

			,MAX(CASE WHEN RANKING = 1 THEN IncomeLossLimit ELSE 0 END) AS IncomeLossLimit01
			,MAX(CASE WHEN RANKING = 2 THEN IncomeLossLimit ELSE 0 END) AS IncomeLossLimit02
			,MAX(CASE WHEN RANKING = 3 THEN IncomeLossLimit ELSE 0 END) AS IncomeLossLimit03
/*			,MAX(CASE WHEN RANKING = 4 THEN IncomeLossLimit ELSE 0 END) AS IncomeLossLimit04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN IncomeLossLimit ELSE 0 END) AS IncomeLossLimit05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN IncomeLossLimit ELSE 0 END) AS IncomeLossLimit99*/

			,MAX(CASE WHEN RANKING = 1 THEN IncomeLossLimit2 ELSE 0 END) AS IncomeLossLimit201
			,MAX(CASE WHEN RANKING = 2 THEN IncomeLossLimit2 ELSE 0 END) AS IncomeLossLimit202
			,MAX(CASE WHEN RANKING = 3 THEN IncomeLossLimit2 ELSE 0 END) AS IncomeLossLimit203
/*			,MAX(CASE WHEN RANKING = 4 THEN IncomeLossLimit2 ELSE 0 END) AS IncomeLossLimit204*/
/*			,MAX(CASE WHEN RANKING = 5 THEN IncomeLossLimit2 ELSE 0 END) AS IncomeLossLimit205*/
/*			,MAX(CASE WHEN RANKING > 5 THEN IncomeLossLimit2 ELSE 0 END) AS IncomeLossLimit299*/

/*			,CoLegalExpense*/
/*			,LegalExpense*/


			,MAX(CASE WHEN RANKING = 1 THEN VEH_CLASS_NAME ELSE "" END) AS VEH_CLASS_NAME01
			,MAX(CASE WHEN RANKING = 2 THEN VEH_CLASS_NAME ELSE "" END) AS VEH_CLASS_NAME02
			,MAX(CASE WHEN RANKING = 3 THEN VEH_CLASS_NAME ELSE "" END) AS VEH_CLASS_NAME03
/*			,MAX(CASE WHEN RANKING = 4 THEN VEH_CLASS_NAME ELSE "" END) AS VEH_CLASS_NAME04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN VEH_CLASS_NAME ELSE "" END) AS VEH_CLASS_NAME05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN VEH_CLASS_NAME ELSE "" END) AS VEH_CLASS_NAME99*/

			,MAX(CASE WHEN RANKING = 1 THEN VEH_SIZE_NAME ELSE "" END) AS VEH_SIZE_NAME01
			,MAX(CASE WHEN RANKING = 2 THEN VEH_SIZE_NAME ELSE "" END) AS VEH_SIZE_NAME02
			,MAX(CASE WHEN RANKING = 3 THEN VEH_SIZE_NAME ELSE "" END) AS VEH_SIZE_NAME03
/*			,MAX(CASE WHEN RANKING = 4 THEN VEH_SIZE_NAME ELSE "" END) AS VEH_SIZE_NAME04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN VEH_SIZE_NAME ELSE "" END) AS VEH_SIZE_NAME05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN VEH_SIZE_NAME ELSE "" END) AS VEH_SIZE_NAME99*/

			,MAX(CASE WHEN RANKING = 1 THEN DRIVE_TYPE ELSE "" END) AS DRIVE_TYPE01
			,MAX(CASE WHEN RANKING = 2 THEN DRIVE_TYPE ELSE "" END) AS DRIVE_TYPE02
			,MAX(CASE WHEN RANKING = 3 THEN DRIVE_TYPE ELSE "" END) AS DRIVE_TYPE03
/*			,MAX(CASE WHEN RANKING = 4 THEN DRIVE_TYPE ELSE "" END) AS DRIVE_TYPE04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN DRIVE_TYPE ELSE "" END) AS DRIVE_TYPE05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN DRIVE_TYPE ELSE "" END) AS DRIVE_TYPE99*/


			,MAX(CASE WHEN RANKING = 1 THEN BODY_CONSTRUCTION ELSE "" END) AS BODY_CONSTRUCTION01
			,MAX(CASE WHEN RANKING = 2 THEN BODY_CONSTRUCTION ELSE "" END) AS BODY_CONSTRUCTION02
			,MAX(CASE WHEN RANKING = 3 THEN BODY_CONSTRUCTION ELSE "" END) AS BODY_CONSTRUCTION03
/*			,MAX(CASE WHEN RANKING = 4 THEN BODY_CONSTRUCTION ELSE "" END) AS BODY_CONSTRUCTION04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN BODY_CONSTRUCTION ELSE "" END) AS BODY_CONSTRUCTION05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN BODY_CONSTRUCTION ELSE "" END) AS BODY_CONSTRUCTION99*/

			,MAX(CASE WHEN RANKING = 1 THEN GRP_CURBWGT_COLCMP ELSE "" END) AS GRP_CURBWGT_COLCMP01
			,MAX(CASE WHEN RANKING = 2 THEN GRP_CURBWGT_COLCMP ELSE "" END) AS GRP_CURBWGT_COLCMP02
			,MAX(CASE WHEN RANKING = 3 THEN GRP_CURBWGT_COLCMP ELSE "" END) AS GRP_CURBWGT_COLCMP03
/*			,MAX(CASE WHEN RANKING = 4 THEN GRP_CURBWGT_COLCMP ELSE "" END) AS GRP_CURBWGT_COLCMP04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN GRP_CURBWGT_COLCMP ELSE "" END) AS GRP_CURBWGT_COLCMP05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN GRP_CURBWGT_COLCMP ELSE "" END) AS GRP_CURBWGT_COLCMP99*/

			,MAX(CASE WHEN RANKING = 1 THEN GRP_AVG_HORSE_BIPDPIPCOL ELSE "" END) AS GRP_AVG_HORSE_BIPDPIPCOL01
			,MAX(CASE WHEN RANKING = 2 THEN GRP_AVG_HORSE_BIPDPIPCOL ELSE "" END) AS GRP_AVG_HORSE_BIPDPIPCOL02
			,MAX(CASE WHEN RANKING = 3 THEN GRP_AVG_HORSE_BIPDPIPCOL ELSE "" END) AS GRP_AVG_HORSE_BIPDPIPCOL03
/*			,MAX(CASE WHEN RANKING = 4 THEN GRP_AVG_HORSE_BIPDPIPCOL ELSE "" END) AS GRP_AVG_HORSE_BIPDPIPCOL04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN GRP_AVG_HORSE_BIPDPIPCOL ELSE "" END) AS GRP_AVG_HORSE_BIPDPIPCOL05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN GRP_AVG_HORSE_BIPDPIPCOL ELSE "" END) AS GRP_AVG_HORSE_BIPDPIPCOL99*/

			,MAX(CASE WHEN RANKING = 1 THEN GRP_VEH_BASE_PRICE_BIPDPIP ELSE "" END) AS GRP_VEH_BASE_PRICE_BIPDPIP01
			,MAX(CASE WHEN RANKING = 2 THEN GRP_VEH_BASE_PRICE_BIPDPIP ELSE "" END) AS GRP_VEH_BASE_PRICE_BIPDPIP02
			,MAX(CASE WHEN RANKING = 3 THEN GRP_VEH_BASE_PRICE_BIPDPIP ELSE "" END) AS GRP_VEH_BASE_PRICE_BIPDPIP03
/*			,MAX(CASE WHEN RANKING = 4 THEN GRP_VEH_BASE_PRICE_BIPDPIP ELSE "" END) AS GRP_VEH_BASE_PRICE_BIPDPIP04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN GRP_VEH_BASE_PRICE_BIPDPIP ELSE "" END) AS GRP_VEH_BASE_PRICE_BIPDPIP05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN GRP_VEH_BASE_PRICE_BIPDPIP ELSE "" END) AS GRP_VEH_BASE_PRICE_BIPDPIP99*/

			,MAX(CASE WHEN RANKING = 1 THEN GRP_DAY_RUN_LIGHT ELSE "" END) AS GRP_DAY_RUN_LIGHT01
			,MAX(CASE WHEN RANKING = 2 THEN GRP_DAY_RUN_LIGHT ELSE "" END) AS GRP_DAY_RUN_LIGHT02
			,MAX(CASE WHEN RANKING = 3 THEN GRP_DAY_RUN_LIGHT ELSE "" END) AS GRP_DAY_RUN_LIGHT03
/*			,MAX(CASE WHEN RANKING = 4 THEN GRP_DAY_RUN_LIGHT ELSE "" END) AS GRP_DAY_RUN_LIGHT04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN GRP_DAY_RUN_LIGHT ELSE "" END) AS GRP_DAY_RUN_LIGHT05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN GRP_DAY_RUN_LIGHT ELSE "" END) AS GRP_DAY_RUN_LIGHT99*/

			,MAX(CASE WHEN RANKING = 1 THEN GRP_ANTI_THEFT ELSE "" END) AS GRP_ANTI_THEFT01
			,MAX(CASE WHEN RANKING = 2 THEN GRP_ANTI_THEFT ELSE "" END) AS GRP_ANTI_THEFT02
			,MAX(CASE WHEN RANKING = 3 THEN GRP_ANTI_THEFT ELSE "" END) AS GRP_ANTI_THEFT03
/*			,MAX(CASE WHEN RANKING = 4 THEN GRP_ANTI_THEFT ELSE "" END) AS GRP_ANTI_THEFT04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN GRP_ANTI_THEFT ELSE "" END) AS GRP_ANTI_THEFT05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN GRP_ANTI_THEFT ELSE "" END) AS GRP_ANTI_THEFT99*/

			,MAX(CASE WHEN RANKING = 1 THEN GRP_BRAKES ELSE "" END) AS GRP_BRAKES01
			,MAX(CASE WHEN RANKING = 2 THEN GRP_BRAKES ELSE "" END) AS GRP_BRAKES02
			,MAX(CASE WHEN RANKING = 3 THEN GRP_BRAKES ELSE "" END) AS GRP_BRAKES03
/*			,MAX(CASE WHEN RANKING = 4 THEN GRP_BRAKES ELSE "" END) AS GRP_BRAKES04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN GRP_BRAKES ELSE "" END) AS GRP_BRAKES05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN GRP_BRAKES ELSE "" END) AS GRP_BRAKES99*/

			,MAX(CASE WHEN RANKING = 1 THEN GRP_ADAPTIVE_CRUISE_CTRL ELSE "" END) AS GRP_ADAPTIVE_CRUISE_CTRL01
			,MAX(CASE WHEN RANKING = 2 THEN GRP_ADAPTIVE_CRUISE_CTRL ELSE "" END) AS GRP_ADAPTIVE_CRUISE_CTRL02
			,MAX(CASE WHEN RANKING = 3 THEN GRP_ADAPTIVE_CRUISE_CTRL ELSE "" END) AS GRP_ADAPTIVE_CRUISE_CTRL03
/*			,MAX(CASE WHEN RANKING = 4 THEN GRP_ADAPTIVE_CRUISE_CTRL ELSE "" END) AS GRP_ADAPTIVE_CRUISE_CTRL04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN GRP_ADAPTIVE_CRUISE_CTRL ELSE "" END) AS GRP_ADAPTIVE_CRUISE_CTRL05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN GRP_ADAPTIVE_CRUISE_CTRL ELSE "" END) AS GRP_ADAPTIVE_CRUISE_CTRL99*/

			,MAX(CASE WHEN RANKING = 1 THEN GRP_CAM_SENSOR ELSE "" END) AS GRP_CAM_SENSOR01
			,MAX(CASE WHEN RANKING = 2 THEN GRP_CAM_SENSOR ELSE "" END) AS GRP_CAM_SENSOR02
			,MAX(CASE WHEN RANKING = 3 THEN GRP_CAM_SENSOR ELSE "" END) AS GRP_CAM_SENSOR03
/*			,MAX(CASE WHEN RANKING = 4 THEN GRP_CAM_SENSOR ELSE "" END) AS GRP_CAM_SENSOR04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN GRP_CAM_SENSOR ELSE "" END) AS GRP_CAM_SENSOR05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN GRP_CAM_SENSOR ELSE "" END) AS GRP_CAM_SENSOR99*/

			,MAX(CASE WHEN RANKING = 1 THEN GRP_BLIND_SPOT ELSE "" END) AS GRP_BLIND_SPOT01
			,MAX(CASE WHEN RANKING = 2 THEN GRP_BLIND_SPOT ELSE "" END) AS GRP_BLIND_SPOT02
			,MAX(CASE WHEN RANKING = 3 THEN GRP_BLIND_SPOT ELSE "" END) AS GRP_BLIND_SPOT03
/*			,MAX(CASE WHEN RANKING = 4 THEN GRP_BLIND_SPOT ELSE "" END) AS GRP_BLIND_SPOT04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN GRP_BLIND_SPOT ELSE "" END) AS GRP_BLIND_SPOT05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN GRP_BLIND_SPOT ELSE "" END) AS GRP_BLIND_SPOT99*/

			,MAX(CASE WHEN RANKING = 1 THEN GRP_ACCIDENT_AVOIDANCE ELSE "" END) AS GRP_ACCIDENT_AVOIDANCE01
			,MAX(CASE WHEN RANKING = 2 THEN GRP_ACCIDENT_AVOIDANCE ELSE "" END) AS GRP_ACCIDENT_AVOIDANCE02
			,MAX(CASE WHEN RANKING = 3 THEN GRP_ACCIDENT_AVOIDANCE ELSE "" END) AS GRP_ACCIDENT_AVOIDANCE03
/*			,MAX(CASE WHEN RANKING = 4 THEN GRP_ACCIDENT_AVOIDANCE ELSE "" END) AS GRP_ACCIDENT_AVOIDANCE04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN GRP_ACCIDENT_AVOIDANCE ELSE "" END) AS GRP_ACCIDENT_AVOIDANCE05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN GRP_ACCIDENT_AVOIDANCE ELSE "" END) AS GRP_ACCIDENT_AVOIDANCE99*/

			,MAX(CASE WHEN RANKING = 1 THEN GRP_LANE_DEPART ELSE "" END) AS GRP_LANE_DEPART01
			,MAX(CASE WHEN RANKING = 2 THEN GRP_LANE_DEPART ELSE "" END) AS GRP_LANE_DEPART02
			,MAX(CASE WHEN RANKING = 3 THEN GRP_LANE_DEPART ELSE "" END) AS GRP_LANE_DEPART03
/*			,MAX(CASE WHEN RANKING = 4 THEN GRP_LANE_DEPART ELSE "" END) AS GRP_LANE_DEPART04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN GRP_LANE_DEPART ELSE "" END) AS GRP_LANE_DEPART05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN GRP_LANE_DEPART ELSE "" END) AS GRP_LANE_DEPART99*/

			,MAX(CASE WHEN RANKING = 1 THEN GRP_ADAPTIVECRUISE_ACCAVOID ELSE "" END) AS GRP_ADAPTIVECRUISE_ACCAVOID01
			,MAX(CASE WHEN RANKING = 2 THEN GRP_ADAPTIVECRUISE_ACCAVOID ELSE "" END) AS GRP_ADAPTIVECRUISE_ACCAVOID02
			,MAX(CASE WHEN RANKING = 3 THEN GRP_ADAPTIVECRUISE_ACCAVOID ELSE "" END) AS GRP_ADAPTIVECRUISE_ACCAVOID03
/*			,MAX(CASE WHEN RANKING = 4 THEN GRP_ADAPTIVECRUISE_ACCAVOID ELSE "" END) AS GRP_ADAPTIVECRUISE_ACCAVOID04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN GRP_ADAPTIVECRUISE_ACCAVOID ELSE "" END) AS GRP_ADAPTIVECRUISE_ACCAVOID05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN GRP_ADAPTIVECRUISE_ACCAVOID ELSE "" END) AS GRP_ADAPTIVECRUISE_ACCAVOID99*/

			,MAX(CASE WHEN RANKING = 1 THEN GRP_BLINDSPOT_LANEDEPT ELSE "" END) AS GRP_BLINDSPOT_LANEDEPT01
			,MAX(CASE WHEN RANKING = 2 THEN GRP_BLINDSPOT_LANEDEPT ELSE "" END) AS GRP_BLINDSPOT_LANEDEPT02
			,MAX(CASE WHEN RANKING = 3 THEN GRP_BLINDSPOT_LANEDEPT ELSE "" END) AS GRP_BLINDSPOT_LANEDEPT03
/*			,MAX(CASE WHEN RANKING = 4 THEN GRP_BLINDSPOT_LANEDEPT ELSE "" END) AS GRP_BLINDSPOT_LANEDEPT04*/
/*			,MAX(CASE WHEN RANKING = 5 THEN GRP_BLINDSPOT_LANEDEPT ELSE "" END) AS GRP_BLINDSPOT_LANEDEPT05*/
/*			,MAX(CASE WHEN RANKING > 5 THEN GRP_BLINDSPOT_LANEDEPT ELSE "" END) AS GRP_BLINDSPOT_LANEDEPT99*/




		FROM &state._Rate_Car03 T1
		LEFT JOIN(SELECT RateId,Term_Adj_Factor FROM work.&state._Rate01) T2 ON 
		T1.RATELINKID = T2.RateId

		GROUP BY 1
;QUIT;

/*Create Policy(Quote) level table from Rate table to get Policy Rate Metrics*/
PROC SQL;
	CREATE TABLE &state._Rate_Metrics02 AS
		SELECT
			 Rate_Metrics01.PolicyLinkID
			,Rate_Metrics01.RateIteration
			,AVG(Rate_Metrics01.TotalPremium_Term_Adj) AS Avg_TotalPremium_Term_Adj
			,MEDIAN(Rate_Metrics01.TotalPremium_Term_Adj) AS Median_TotalPremium_Term_Adj
			/*add DTM x Company column*/
/*			,(sum(Rate_Metrics01.TotalPremium_Term_Adj) over (Partition By Rate_Metrics01.PolicyLinkID)-Rate_Metrics01.TotalPremium_Term_Adj)/NullIf((sum(1) over (Partition By Rate_Metrics01.PolicyLinkID)-1),0) as New_Median*/
			,MAX(Rate_Metrics01.TotalPremium_Term_Adj) AS Max_TotalPremium_Term_Adj
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 1 THEN Rate_Metrics01.TotalPremium_Term_Adj ELSE 0 END) AS TotalPremium_Term_Adj01
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 2 THEN Rate_Metrics01.TotalPremium_Term_Adj ELSE 0 END) AS TotalPremium_Term_Adj02
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 3 THEN Rate_Metrics01.TotalPremium_Term_Adj ELSE 0 END) AS TotalPremium_Term_Adj03
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 4 THEN Rate_Metrics01.TotalPremium_Term_Adj ELSE 0 END) AS TotalPremium_Term_Adj04
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 5 THEN Rate_Metrics01.TotalPremium_Term_Adj ELSE 0 END) AS TotalPremium_Term_Adj05
			,COUNT(Rate_Metrics01.TotalPremium_Term_Adj) As NumCompetitors
			,MAX(CASE WHEN ROUND(Rate_Metrics01.CompanyID/10000,1) IN (12623,12622) THEN 1 ELSE 0 END) AS GCQUOTED

			,MAX(CASE WHEN Rate_Metrics01.RANKING = 1 THEN TRIMN(Rate_Metrics01.Company_Name)||COMPRESS(Rate_Metrics01.Program) ELSE "" END) AS Company_Name01
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 2 THEN TRIMN(Rate_Metrics01.Company_Name)||COMPRESS(Rate_Metrics01.Program) ELSE "" END) AS Company_Name02
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 3 THEN TRIMN(Rate_Metrics01.Company_Name)||COMPRESS(Rate_Metrics01.Program) ELSE "" END) AS Company_Name03
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 4 THEN TRIMN(Rate_Metrics01.Company_Name)||COMPRESS(Rate_Metrics01.Program) ELSE "" END) AS Company_Name04
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 5 THEN TRIMN(Rate_Metrics01.Company_Name)||COMPRESS(Rate_Metrics01.Program) ELSE "" END) AS Company_Name05

		FROM &state._Rate_Metrics01 Rate_Metrics01
		WHERE TotalPremium_Term_Adj NE 0
		GROUP BY 1,2
;QUIT;

PROC SQL;
	CREATE TABLE &state._COV_PREM01 AS
		SELECT
			 Rate_Metrics01.PolicyLinkID
			,Rate_Metrics01.RateIteration
			,MEDIAN(Rate_Car03.LiabBIPremium) AS Median_LiabBIPremium
			,MEDIAN(Rate_Car03.LiabPDPremium) AS Median_LiabPDPremium
			,MEDIAN(Rate_Car03.MedPayPremium) AS Median_MedPayPremium
			,MEDIAN(Rate_Car03.PIPPremium) AS Median_PIPPremium
			,MEDIAN(Rate_Car03.RentalPremium) AS Median_RentalPremium
			,MEDIAN(Rate_Car03.TowingPremium) AS Median_TowingPremium
			,MEDIAN(Rate_Car03.UIMBIPremium) AS Median_UIMBIPremium
			,MEDIAN(Rate_Car03.UIMPDPremium) AS Median_UIMPDPremium
			,MEDIAN(Rate_Car03.UninsBIPremium) AS Median_UninsBIPremium
			,MEDIAN(Rate_Car03.UninsPDPremium) AS Median_UninsPDPremium
			,MEDIAN(Rate_Car03.CompPremium) AS Median_CompPremium
			,MEDIAN(Rate_Car03.CollPremium) AS Median_CollPremium

			,MAX(CASE WHEN Rate_Metrics01.RANKING = 1 THEN Rate_Car03.LiabBIPremium ELSE 0 END) AS LiabBIPremium01
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 1 THEN Rate_Car03.LiabPDPremium ELSE 0 END) AS LiabPDPremium01
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 1 THEN Rate_Car03.MedPayPremium ELSE 0 END) AS MedPayPremium01
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 1 THEN Rate_Car03.PIPPremium ELSE 0 END) AS PIPPremium01
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 1 THEN Rate_Car03.RentalPremium ELSE 0 END) AS RentalPremium01
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 1 THEN Rate_Car03.TowingPremium ELSE 0 END) AS TowingPremium01
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 1 THEN Rate_Car03.UIMBIPremium ELSE 0 END) AS UIMBIPremium01
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 1 THEN Rate_Car03.UIMPDPremium ELSE 0 END) AS UIMPDPremium01
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 1 THEN Rate_Car03.UninsBIPremium ELSE 0 END) AS UninsBIPremium01
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 1 THEN Rate_Car03.UninsPDPremium ELSE 0 END) AS UninsPDPremium01
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 1 THEN Rate_Car03.CompPremium ELSE 0 END) AS CompPremium01
			,MAX(CASE WHEN Rate_Metrics01.RANKING = 1 THEN Rate_Car03.CollPremium ELSE 0 END) AS CollPremium01

		FROM &state._Rate_Metrics01 Rate_Metrics01

		LEFT JOIN &state._Rate_Car03 Rate_Car03 ON Rate_Metrics01.RateId = Rate_Car03.RateLinkID


		GROUP BY 1,2
;QUIT;
