
use[Marketing]
Select sum(Quotes) as Quote, Company, sum(TOTAL_PREMIUM) as Total_Premium, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,zip

From (SELECT COUNT(TOTPREM) AS QUOTES, COMPANY, SUM(TOTPREM) AS TOTAL_PREMIUM, POP, AREA AS RISKAREA, PLEVEL AS P_LEVEL, TRANSYY AS QUOTE_YEAR, TRANSMM AS QUOTE_MM, VYR AS MODELYEAR,
		[PROFILE], NUMDRIV AS DRVCNT, NUMVEHL AS VEHCNT, TERM, 'SC' AS [STATE],zip,
		CASE WHEN RANK1DIFF <=0   THEN 'WIN'
			 WHEN RANK1DIFF <=30  THEN '1_30'
			 WHEN RANK1DIFF <=60  THEN '31_60'
			 WHEN RANK1DIFF <=90  THEN '61_90'
			 WHEN RANK1DIFF <=120 THEN '91_120'
			 ELSE 'GE_121' END AS LABEL
  FROM [MARKETING].[DBO].[SC_MB]
  where Company like '%GAIN%'
  GROUP BY COMPANY, TOTPREM, AREA, PLEVEL, TRANSYY , TRANSMM, VYR,
		[PROFILE], NUMDRIV , NUMVEHL, CASE WHEN RANK1DIFF <=0   THEN 'WIN'
			 WHEN RANK1DIFF <=30  THEN '1_30'
			 WHEN RANK1DIFF <=60  THEN '31_60'
			 WHEN RANK1DIFF <=90  THEN '61_90'
			 WHEN RANK1DIFF <=120 THEN '91_120'
			 ELSE 'GE_121' END, POP, TERM,zip
	) as a 

Group by Company, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,zip

UNION All

Select sum(Quotes) as Quote, Company, sum(TOTAL_PREMIUM) as Total_Premium, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,Zip

From (SELECT COUNT(TOTPREM) AS QUOTES, COMPANY, SUM(TOTPREM) AS TOTAL_PREMIUM, POP, AREA AS RISKAREA, PLEVEL AS P_LEVEL, TRANSYY AS QUOTE_YEAR, TRANSMM AS QUOTE_MM, VYR AS MODELYEAR,
		[PROFILE], NUMDRIV AS DRVCNT, NUMVEHL AS VEHCNT, TERM, 'FL' AS [STATE],Zip,
		CASE WHEN RANK1DIFF <=0   THEN 'WIN'
			 WHEN RANK1DIFF <=30  THEN '1_30'
			 WHEN RANK1DIFF <=60  THEN '31_60'
			 WHEN RANK1DIFF <=90  THEN '61_90'
			 WHEN RANK1DIFF <=120 THEN '91_120'
			 ELSE 'GE_121' END AS LABEL
  FROM [MARKETING].[DBO].[FL_MB]
  where Company like '%GAIN%'
  GROUP BY COMPANY, TOTPREM, AREA, PLEVEL, TRANSYY , TRANSMM, VYR,
		[PROFILE], NUMDRIV , NUMVEHL, CASE WHEN RANK1DIFF <=0   THEN 'WIN'
			 WHEN RANK1DIFF <=30  THEN '1_30'
			 WHEN RANK1DIFF <=60  THEN '31_60'
			 WHEN RANK1DIFF <=90  THEN '61_90'
			 WHEN RANK1DIFF <=120 THEN '91_120'
			 ELSE 'GE_121' END, POP, TERM,Zip
		) as a
Group by Company, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,Zip

UNION All

 Select sum(Quotes) as Quote, Company, sum(TOTAL_PREMIUM) as Total_Premium, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,zip

From (SELECT COUNT(TOTPREM) AS QUOTES, COMPANY, SUM(TOTPREM) AS TOTAL_PREMIUM, POP, MARKET AS RISKAREA, PLEVEL AS P_LEVEL, TRANSYY AS QUOTE_YEAR, TRANSMM AS QUOTE_MM, VYR AS MODELYEAR,
		[PROFILE], NUMDRIV AS DRVCNT, NUMVEHL AS VEHCNT, '6' AS TERM, 'GA' AS [STATE],zip,
		CASE WHEN RANK1DIFF <=0   THEN 'WIN'
			 WHEN RANK1DIFF <=30  THEN '1_30'
			 WHEN RANK1DIFF <=60  THEN '31_60'
			 WHEN RANK1DIFF <=90  THEN '61_90'
			 WHEN RANK1DIFF <=120 THEN '91_120'
			 ELSE 'GE_121' END AS LABEL
  FROM [MARKETING].[DBO].[GA_MB]
  where Company like '%GAIN%'
  GROUP BY COMPANY, TOTPREM, MARKET, PLEVEL, TRANSYY , TRANSMM, VYR,
		[PROFILE], NUMDRIV , NUMVEHL, CASE WHEN RANK1DIFF <=0   THEN 'WIN'
			 WHEN RANK1DIFF <=30  THEN '1_30'
			 WHEN RANK1DIFF <=60  THEN '31_60'
			 WHEN RANK1DIFF <=90  THEN '61_90'
			 WHEN RANK1DIFF <=120 THEN '91_120'
			 ELSE 'GE_121' END, POP,zip
		) as a 
where ( Company like '%Gainsco%')
Group by Company, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,zip

UNION All


Select sum(Quotes) as Quote, Company, sum(TOTAL_PREMIUM) as Total_Premium, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode

From (SELECT COUNT(TOTPREM) AS QUOTES, CO_NAME AS COMPANY, SUM(TOTPREM) AS TOTAL_PREMIUM, CASE WHEN POP = 1 THEN 'Y' ELSE 'N' END AS POP, RISKAREA, P_LEVEL, 
		RATE_YR AS QUOTE_YEAR, RATE_MO AS QUOTE_MM, [YEAR] AS MODELYEAR,
		[PROFILE], DRCNT AS DRVCNT, VEHCNT AS VEHCNT, TERM, 'TN' AS [STATE],ZipCode,
		CASE WHEN (TOTPREM - RANK1PR) <=0  THEN 'WIN'
		     WHEN (TOTPREM - RANK1PR) <=30 THEN '1_30'
			 WHEN (TOTPREM - RANK1PR) <=60 THEN '31_60'
			 WHEN (TOTPREM - RANK1PR) <=90 THEN '61_90'
			 WHEN (TOTPREM - RANK1PR) <=120 THEN '91_120'
			 ELSE 'GE_121' END AS LABEL
  FROM [MARKETING].[DBO].[TN_MB]
  where CO_Name like '%GAIN%'
  GROUP BY CO_NAME, POP, RISKAREA, P_LEVEL, RATE_YR , RATE_MO, [YEAR],ZipCode,
		[PROFILE], DRCNT , VEHCNT, POP, CASE WHEN (TOTPREM - RANK1PR) <=0  THEN 'WIN'
		     WHEN (TOTPREM - RANK1PR) <=30 THEN '1_30'
			 WHEN (TOTPREM - RANK1PR) <=60 THEN '31_60'
			 WHEN (TOTPREM - RANK1PR) <=90 THEN '61_90'
			 WHEN (TOTPREM - RANK1PR) <=120 THEN '91_120'
			 ELSE 'GE_121' END, TERM
		) as a 

Group by Company, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode

UNION All




Select sum(Quotes) as Quote, Company, sum(TOTAL_PREMIUM) as Total_Premium, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode

From (SELECT COUNT(TOTPREM) AS QUOTES, CO_NAME AS COMPANY, SUM(TOTPREM) AS TOTAL_PREMIUM, CASE WHEN POP = 1 THEN 'Y' ELSE 'N' END AS POP, RISKAREA, P_LEVEL, ZipCode,
		RATE_YR AS QUOTE_YEAR, RATE_MO AS QUOTE_MM, [YEAR] AS MODELYEAR, 
		[PROFILE], DRCNT AS DRVCNT, VEHCNT AS VEHCNT, TERM, 'VA' AS [STATE],
		CASE WHEN (TOTPREM - RANK1PR) <=0  THEN 'WIN'
		     WHEN (TOTPREM - RANK1PR) <=30 THEN '1_30'
			 WHEN (TOTPREM - RANK1PR) <=60 THEN '31_60'
			 WHEN (TOTPREM - RANK1PR) <=90 THEN '61_90'
			 WHEN (TOTPREM - RANK1PR) <=120 THEN '91_120'
			 ELSE 'GE_121' END AS LABEL
  FROM [MARKETING].[DBO].[VA_MB]
  where CO_Name like '%GAIN%'
  GROUP BY CO_NAME, CASE WHEN (TOTPREM - RANK1PR) <=0  THEN 'WIN'
		     WHEN (TOTPREM - RANK1PR) <=30 THEN '1_30'
			 WHEN (TOTPREM - RANK1PR) <=60 THEN '31_60'
			 WHEN (TOTPREM - RANK1PR) <=90 THEN '61_90'
			 WHEN (TOTPREM - RANK1PR) <=120 THEN '91_120'
			 ELSE 'GE_121' END, POP, RISKAREA, P_LEVEL, RATE_YR , RATE_MO, [YEAR], ZipCode, 
		[PROFILE], DRCNT , VEHCNT, POP, TERM
		) as a 
Group by Company, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode

UNION All

Select sum(Quotes) as Quote, Company, sum(TOTAL_PREMIUM) as Total_Premium, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode

From (SELECT COUNT(TOTPREM) AS QUOTES, CO_NAME AS COMPANY, SUM(TOTPREM) AS TOTAL_PREMIUM, CASE WHEN POP = 1 THEN 'Y' ELSE 'N' END AS POP, RISKAREA, P_LEVEL, ZipCode,
		RATE_YR AS QUOTE_YEAR, RATE_MO AS QUOTE_MM, [YEAR] AS MODELYEAR, 
		[PROFILE], DRCNT AS DRVCNT, VEHCNT AS VEHCNT, '6' as TERM, 'AZ' AS [STATE], LABELS AS LABEL
  FROM [MARKETING].[DBO].[AZ_MB]
  where CO_Name like '%GAIN%'
  GROUP BY CO_NAME, TOTPREM, CASE WHEN POP = 1 THEN 'Y' ELSE 'N' END, RISKAREA, P_LEVEL, RATE_YR, RATE_MO, [YEAR],ZipCode,
		[PROFILE], DRCNT , VEHCNT, POP, LABELS
	) as a 

Group by Company, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode

UNION All

Select sum(Quotes) as Quote, Company, sum(TOTAL_PREMIUM) as Total_Premium, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode

From (SELECT COUNT(TOTPREM) AS QUOTES, CO_NAME AS COMPANY, SUM(TOTPREM) AS TOTAL_PREMIUM, CASE WHEN POP = 1 THEN 'Y' ELSE 'N' END AS POP, RISKAREA, P_LEVEL, ZipCode,
		RATE_YR AS QUOTE_YEAR, RATE_MO AS QUOTE_MM, [YEAR] AS MODELYEAR, 
		[PROFILE], DRCNT AS DRVCNT, VEHCNT AS VEHCNT, '6' as TERM, 'NM' AS [STATE], LABELS AS LABEL
  FROM [MARKETING].[DBO].[NM_MB_VCP]
  where CO_Name like '%GAIN%'
  GROUP BY CO_NAME, TOTPREM, CASE WHEN POP = 1 THEN 'Y' ELSE 'N' END, RISKAREA, P_LEVEL, RATE_YR, RATE_MO, [YEAR], ZipCode,
		[PROFILE], DRCNT , VEHCNT, POP, LABELS
	) as a 
Group by Company, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode

UNION All

Select sum(Quotes) as Quote, Company, sum(TOTAL_PREMIUM) as Total_Premium, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode

From (SELECT COUNT(TOTPREM) AS QUOTES, CO_NAME AS COMPANY, SUM(TOTPREM) AS TOTAL_PREMIUM, CASE WHEN POP = 1 THEN 'Y' ELSE 'N' END AS POP, RISKAREA, P_LEVEL, ZipCode,
		RATE_YR AS QUOTE_YEAR, RATE_MO AS QUOTE_MM, [YEAR] AS MODELYEAR, 
		[PROFILE], DRCNT AS DRVCNT, VEHCNT AS VEHCNT, '6' AS TERM, 'OK' AS [STATE], LABELS AS LABEL
  FROM [MARKETING].[DBO].[OK_MB]
  where CO_Name like '%GAIN%'
  GROUP BY CO_NAME, TOTPREM, POP, RISKAREA, P_LEVEL, RATE_MO, [YEAR], 
		[PROFILE], DRCNT , VEHCNT, CASE WHEN POP = 1 THEN 'Y' ELSE 'N' END, LABELS, RATE_YR,ZipCode
	) as a
Group by Company, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode

UNION All

Select sum(Quotes) as Quote, Company, sum(TOTAL_PREMIUM) as Total_Premium, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode
From (SELECT COUNT(TOTPREM) AS QUOTES, CO_NAME AS COMPANY, SUM(TOTPREM) AS TOTAL_PREMIUM, CASE WHEN POP = 1 THEN 'Y' ELSE 'N' END AS POP, RISKAREA, P_LEVEL, ZipCode,
		RATE_YR AS QUOTE_YEAR, RATE_MO AS QUOTE_MM, [YEAR] AS MODELYEAR,
		[PROFILE], DRCNT AS DRVCNT, VEHCNT AS VEHCNT, '6' AS TERM, 'TX' AS [STATE], LABELS AS LABEL
  FROM [MARKETING].[DBO].[TX_MB]
  where CO_Name like '%GAIN%'
  GROUP BY CO_NAME, TOTPREM, POP, RISKAREA, P_LEVEL, RATE_MO, [YEAR],
		[PROFILE], DRCNT , VEHCNT, CASE WHEN POP = 1 THEN 'Y' ELSE 'N' END, LABELS, RATE_YR,ZipCode
		) as a 

 Group by Company, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode

UNION All

Select sum(Quotes) as Quote, Company, sum(TOTAL_PREMIUM) as Total_Premium, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,zipcode

From (SELECT COUNT(TOTPREM) AS QUOTES, CARRIER AS COMPANY, SUM(TOTPREM) AS TOTAL_PREMIUM, POP, RISK_AREA AS RISKAREA, P_LEVEL,a.ZIP as zipcode,
		Q_YEAR AS QUOTE_YEAR, Q_MONTH AS QUOTE_MM, [YEAR] AS MODELYEAR,
		PROFILEP AS [PROFILE], DRVCNT, VEHCNT AS VEHCNT, '6' AS TERM, 'UT' AS [STATE], LABEL 
  FROM [MARKETING].[DBO].[UT_MB_SUBSET] AS A LEFT JOIN DBO.TERRKEY AS B ON A.ZIP = B.ZIP
  where a.CARRIER like '%GAIN%'
  GROUP BY CARRIER, TOTPREM, POP, RISK_AREA, P_LEVEL, Q_MONTH, [YEAR],
		PROFILEP, DRVCNT , VEHCNT, POP, LABEL, Q_YEAR,a.ZIP
	) as a
Group by Company, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,zipcode

UNION All

Select sum(Quotes) as Quote, Company, sum(TOTAL_PREMIUM) as Total_Premium, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERMCO, [State], LABEL,ZipCode

From (SELECT COUNT(TOTPREM) AS QUOTES, CO_Name as Company, SUM(TOTPREM) AS TOTAL_PREMIUM, case when POP = 0 then 'N' else 'Y' end as POP , RiskArea AS RISKAREA, P_Lvl_tot AS P_LEVEL, Rate_Yr AS QUOTE_YEAR, Rate_Mo AS QUOTE_MM, [Year] AS MODELYEAR,
		[PROFILE], DRCNT AS DRVCNT, VEHCNT AS VEHCNT, TERMCO, 'GA' AS [STATE],ZipCode,
		CASE WHEN DOLDIFF1 <=0   THEN 'WIN'
			 WHEN DOLDIFF1 <=30  THEN '1_30'
			 WHEN DOLDIFF1 <=60  THEN '31_60'
			 WHEN DOLDIFF1 <=90  THEN '61_90'
			 WHEN DOLDIFF1 <=120 THEN '91_120'
			 ELSE 'GE_121' END AS LABEL
  FROM [MARKETING].[DBO].[GA_ITC]
  WHERE (Rate_Yr*100+Rate_Mo) >= 201911 and CO_Name like '%GAIN%'
  GROUP BY CO_Name, TOTPREM, RiskArea, P_Lvl_tot, Rate_Yr , Rate_Mo, [Year],ZipCode,
		[PROFILE], DRCNT , VEHCNT, CASE WHEN DOLDIFF1 <=0   THEN 'WIN'
			 WHEN DOLDIFF1 <=30  THEN '1_30'
			 WHEN DOLDIFF1 <=60  THEN '31_60'
			 WHEN DOLDIFF1 <=90  THEN '61_90'
			 WHEN DOLDIFF1 <=120 THEN '91_120'
			 ELSE 'GE_121' END, POP, TERMCO
		) as a
Group by Company, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERMCO, [State], LABEL,ZipCode

UNION All

Select sum(Quotes) as Quote, Company, sum(TOTAL_PREMIUM) as Total_Premium, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode

From (SELECT COUNT(TOTPREM) AS QUOTES, CO_Name as Company, SUM(TOTPREM) AS TOTAL_PREMIUM, case when POP = 0 then 'N' else 'Y' end as POP, RiskArea AS RISKAREA, P_Level AS P_LEVEL, Rate_Yr AS QUOTE_YEAR, Rate_Mo AS QUOTE_MM, [Year] AS MODELYEAR,
		[PROFILE], DRCNT AS DRVCNT, VEHCNT AS VEHCNT, TERM, 'FL' AS [STATE],ZipCode,
		CASE WHEN DOLDIFF1 <=0   THEN 'WIN'
			 WHEN DOLDIFF1 <=30  THEN '1_30'
			 WHEN DOLDIFF1 <=60  THEN '31_60'
			 WHEN DOLDIFF1 <=90  THEN '61_90'
			 WHEN DOLDIFF1 <=120 THEN '91_120'
			 ELSE 'GE_121' END AS LABEL
  FROM [MARKETING].[DBO].[FL_ITC]
  Where (Rate_Yr*100+Rate_Mo) >= 201911 and CO_Name like '%GAIN%'
  GROUP BY CO_Name, TOTPREM, RiskArea, P_Level, Rate_Yr , Rate_Mo, [Year],ZipCode,
		[PROFILE], DRCNT , VEHCNT, CASE WHEN DOLDIFF1 <=0   THEN 'WIN'
			 WHEN DOLDIFF1 <=30  THEN '1_30'
			 WHEN DOLDIFF1 <=60  THEN '31_60'
			 WHEN DOLDIFF1 <=90  THEN '61_90'
			 WHEN DOLDIFF1 <=120 THEN '91_120'
			 ELSE 'GE_121' END, POP, TERM
		) as a
Group by Company, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode

UNION All

Select sum(Quotes) as Quote, Company, sum(TOTAL_PREMIUM) as Total_Premium, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode

From (SELECT COUNT(TOTPREM) AS QUOTES, CO_Name as Company, SUM(TOTPREM) AS TOTAL_PREMIUM, case when POP = 0 then 'N' else 'Y' end as POP , RiskArea AS RISKAREA, P_Level AS P_LEVEL, Rate_Yr AS QUOTE_YEAR, Rate_Mo AS QUOTE_MM, [Year] AS MODELYEAR,
		[PROFILE], DRCNT AS DRVCNT, VEHCNT AS VEHCNT, TERM, 'SC' AS [STATE],ZipCode,
		CASE WHEN DOLDIFF1 <=0   THEN 'WIN'
			 WHEN DOLDIFF1 <=30  THEN '1_30'
			 WHEN DOLDIFF1 <=60  THEN '31_60'
			 WHEN DOLDIFF1 <=90  THEN '61_90'
			 WHEN DOLDIFF1 <=120 THEN '91_120'
			 ELSE 'GE_121' END AS LABEL
  FROM [MARKETING].[DBO].[SC_ITC]
  WHERE (Rate_Yr*100+Rate_Mo) >= 201911 and CO_Name like '%GAIN%'
  GROUP BY CO_Name, TOTPREM, RiskArea, P_Level, Rate_Yr , Rate_Mo, [Year],ZipCode,
		[PROFILE], DRCNT , VEHCNT, CASE WHEN DOLDIFF1 <=0   THEN 'WIN'
			 WHEN DOLDIFF1 <=30  THEN '1_30'
			 WHEN DOLDIFF1 <=60  THEN '31_60'
			 WHEN DOLDIFF1 <=90  THEN '61_90'
			 WHEN DOLDIFF1 <=120 THEN '91_120'
			 ELSE 'GE_121' END, POP, TERM
		) as a
Group by Company, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode

UNION ALL

Select sum(Quotes) as Quote, Company, sum(TOTAL_PREMIUM) as Total_Premium, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode

From (SELECT COUNT(TOTPREM) AS QUOTES, CO_NAME AS COMPANY, SUM(TOTPREM) AS TOTAL_PREMIUM, CASE WHEN POP = 1 THEN 'Y' ELSE 'N' END AS POP, RISKAREA, P_LEVEL, ZipCode,
		RATE_YR AS QUOTE_YEAR, RATE_MO AS QUOTE_MM, [YEAR] AS MODELYEAR, 
		[PROFILE], DRCNT AS DRVCNT, VEHCNT AS VEHCNT, '6' AS TERM, 'OK' AS [STATE], LABELS AS LABEL
  FROM [MARKETING].[DBO].[OK_MB_VCP] 
  WHERE (Rate_Yr*100+Rate_Mo) >= 201912 and CO_Name like '%GAIN%'
  GROUP BY CO_NAME, TOTPREM, POP, RISKAREA, P_LEVEL, RATE_MO, [YEAR], 
		[PROFILE], DRCNT , VEHCNT, CASE WHEN POP = 1 THEN 'Y' ELSE 'N' END, LABELS, RATE_YR,ZipCode
	) as a
Group by Company, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode

UNION ALL
/*AL*/
Select sum(Quotes) as Quote, Company, sum(TOTAL_PREMIUM) as Total_Premium, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,zipcode

From (SELECT COUNT(TOTPREM) AS QUOTES, CO_Name as Company, SUM(TOTPREM) AS TOTAL_PREMIUM, case when POP = 0 then 'N' else 'Y' end as POP , b.Risk_Area AS RISKAREA, b.P_LEVEL AS P_LEVEL, Rate_Yr AS QUOTE_YEAR, Rate_Mo AS QUOTE_MM, [Year] AS MODELYEAR,
		[PROFILE], DRCNT AS DRVCNT, VEHCNT AS VEHCNT, TERM, 'AL' AS [STATE],a.ZipCode as zipcode,
		CASE WHEN DOLDIFF1 <=0   THEN 'WIN'
			 WHEN DOLDIFF1 <=30  THEN '1_30'
			 WHEN DOLDIFF1 <=60  THEN '31_60'
			 WHEN DOLDIFF1 <=90  THEN '61_90'
			 WHEN DOLDIFF1 <=120 THEN '91_120'
			 ELSE 'GE_121' END AS LABEL
  FROM [MARKETING].[DBO].[AL_ITC] as a left join dbo.[TerrKey] as b on a.ZipCode = b.ZIP
  WHERE (Rate_Yr*100+Rate_Mo) >= 201911 and CO_Name like '%GAINS%'
  GROUP BY CO_Name, TOTPREM, b.RISK_AREA, b.P_LEVEL, Rate_Yr , Rate_Mo, [Year],
		[PROFILE], DRCNT , VEHCNT, CASE WHEN DOLDIFF1 <=0   THEN 'WIN'
			 WHEN DOLDIFF1 <=30  THEN '1_30'
			 WHEN DOLDIFF1 <=60  THEN '31_60'
			 WHEN DOLDIFF1 <=90  THEN '61_90'
			 WHEN DOLDIFF1 <=120 THEN '91_120'
			 ELSE 'GE_121' END, POP, TERM, a.ZipCode
		) as a
Group by Company, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,zipcode

UNION ALL
Select sum(Quotes) as Quote, Company, sum(TOTAL_PREMIUM) as Total_Premium, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode

From (SELECT COUNT(TOTPREM) AS QUOTES, CO_NAME AS COMPANY, SUM(TOTPREM) AS TOTAL_PREMIUM, CASE WHEN POP = 1 THEN 'Y' ELSE 'N' END AS POP, RISKAREA, P_LEVEL, ZipCode,
		RATE_YR AS QUOTE_YEAR, RATE_MO AS QUOTE_MM, [YEAR] AS MODELYEAR, 
		[PROFILE], DRCNT AS DRVCNT, VEHCNT AS VEHCNT, '6' as TERM, 'AZ' AS [STATE], LABELS AS LABEL
  FROM [MARKETING].[DBO].[AZ_MB_VCP]
  where CO_Name like '%GAIN%'
  GROUP BY CO_NAME, TOTPREM, CASE WHEN POP = 1 THEN 'Y' ELSE 'N' END, RISKAREA, P_LEVEL, RATE_YR, RATE_MO, [YEAR],ZipCode,
		[PROFILE], DRCNT , VEHCNT, POP, LABELS
	) as a 

Group by Company, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL,ZipCode


