use [Marketing]
go
Select sum(Quotes) as Quote, Company, sum(TOTAL_PREMIUM) as Total_Premium, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL

From (SELECT COUNT(TOTPREM) AS QUOTES, CARRIER AS COMPANY, SUM(TOTPREM) AS TOTAL_PREMIUM, POP, RISK_AREA AS RISKAREA, P_LEVEL, 
		Q_YEAR AS QUOTE_YEAR, Q_MONTH AS QUOTE_MM, [YEAR] AS MODELYEAR,
		PROFILEP AS [PROFILE], DRVCNT, VEHCNT AS VEHCNT, '6' AS TERM, 'UT' AS [STATE], LABEL
  FROM [MARKETING].[DBO].[UT_MB] AS A LEFT JOIN DBO.TERRKEY AS B ON A.ZIP = B.ZIP
  GROUP BY CARRIER, TOTPREM, POP, RISK_AREA, P_LEVEL, Q_MONTH, [YEAR],
		PROFILEP, DRVCNT , VEHCNT, POP, LABEL, Q_YEAR
	) as a
Group by Company, POP, RISKAREA, P_LEVEL, QUOTE_YEAR, QUOTE_MM, MODELYEAR, [Profile], DRVCNT, VEHCNT, TERM, [State], LABEL