use [GainscoConnect]
go 
;WITH T1 AS (

SELECT *

FROM(

	SELECT A.POLICYNUMBER, A.PACKAGEID, A.PACKAGENAME, A.SENDEREMAIL, A.DATECREATED, A.AGENTEMAIL, A.INSUREDEMAIL, A.SIGNINGMETHOD, 
	A.AGENTCODE, A.EFFECTIVEDATE, A.SIGNURL, B.DATECREATED AS ACTDATE, B.EVENT, ROW_NUMBER() OVER (PARTITION BY A.POLICYNUMBER,
	CONVERT(NVARCHAR(50), A.EFFECTIVEDATE, 111) ORDER BY A.DATECREATED DESC) AS DUPE, year(a.DateCreated)*100+month(a.DateCreated) as YYYYMM

	FROM GAINSCOCONNECT.ESIGN.PACKAGE A WITH (NOLOCK)
	INNER JOIN (SELECT * FROM GAINSCOCONNECT.ESIGN.EVENT AS TEMP WHERE TEMP.EVENT= 'PACKAGE_COMPLETE') AS B
	ON A.PACKAGEID = B.PACKAGEID

	WHERE EFFECTIVEDATE >= '2018-1-1' AND A.PACKAGENAME IN ('REW', 'NEW') AND A.AGENTCODE NOT LIKE '%A9%'

	) AS TBL1

WHERE TBL1.EVENT= 'PACKAGE_COMPLETE' AND TBL1.DUPE = 1),

T2 AS (

SELECT *

FROM(

	SELECT A.POLICYNUMBER, A.PACKAGEID, A.PACKAGENAME, A.SENDEREMAIL, A.DATECREATED, A.AGENTEMAIL, A.INSUREDEMAIL, A.SIGNINGMETHOD,
	A.AGENTCODE, A.EFFECTIVEDATE, A.SIGNURL, B.DATECREATED AS ACTDATE, B.EVENT, ROW_NUMBER() OVER (PARTITION BY A.POLICYNUMBER,
	CONVERT(NVARCHAR(50), A.EFFECTIVEDATE, 111) ORDER BY B.DATECREATED DESC) AS DUPE, year(a.DateCreated)*100+month(a.DateCreated) as YYYYMM

	FROM GAINSCOCONNECT.ESIGN.PACKAGE A WITH (NOLOCK)
	LEFT JOIN GAINSCOCONNECT.ESIGN.EVENT B ON A.PACKAGEID=B.PACKAGEID

	WHERE EFFECTIVEDATE >= '2018-1-1' AND A.PACKAGENAME IN ('REW', 'NEW') AND A.AGENTCODE NOT LIKE '%A999%'

) AS TBL2

WHERE DUPE = 1 AND EVENT <>'PACKAGE_COMPLETE')


SELECT *
FROM T1
UNION
SELECT *
FROM T2 
WHERE NOT EXISTS (
	SELECT *
	FROM T1
	WHERE T1.POLICYNUMBER = T2.POLICYNUMBER
)