%let ITC_EXT = W:\Product\Schwartz_Jonah\ITC_MB\ITC_EXTRACTS\;
libname output '\\DALGRP01\RiskManagementGrpshare\Product\ITC_MarketBasket\DATA\FULL_DATA\';
/*LIBNAME ITC_OUT 'W:\Product\Schwartz_Jonah\ITC_MB\ITC_OUTPUTS';*/
LIBNAME D_ANDYD ODBC USER=AUDIT1 PASSWORD=audit11 DATASRC=DRAGON SCHEMA=ANDYD;
LIBNAME D_EOM ODBC USER=AUDIT1 PASSWORD=audit11 DATASRC=DRAGON SCHEMA=LDSNEWEOM;
LIBNAME D_FIL ODBC USER=AUDIT1 PASSWORD=audit11 DATASRC=DRAGON SCHEMA=LDSNEWFIL;
LIBNAME D_QRY ODBC USER=AUDIT1 PASSWORD=audit11 DATASRC=DRAGON SCHEMA=LDSNEWQRY;
LIBNAME D_TBL ODBC USER=AUDIT1 PASSWORD=audit11 DATASRC=DRAGON SCHEMA=LDSNEWTBL;
LIBNAME D_WRK ODBC USER=AUDIT1 PASSWORD=audit11 DATASRC=DRAGON SCHEMA=LDSNEWWRK;
LIBNAME D_NSLFIL ODBC USER=AUDIT1 PASSWORD=audit11 DATASRC=DRAGON SCHEMA=NSLFILES;

LIBNAME MARK ODBC READ_ISOLATION_LEVEL = RU SCHEMA=DBO 
DBCOMMIT=100000 INSERTBUFF=10000 BULKLOAD=YES CONNECTION=SHARED
DBMAX_TEXT=32767 /* PREVENT TEXT COLUMN TRUNCATION */
REQUIRED=
"DRIVER=SQL SERVER;
DATABASE=MARKETING;
SERVER=DALDBCP06\REPORTING;";
